// Generated by PayloadTemplates.cloudflarePayload — regenerate, do not edit
import type React from 'react'

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ font: '15px/1.55 system-ui, sans-serif', maxWidth: 1100, margin: '2rem auto', padding: '0 1rem' }}>{children}</body>
    </html>
  )
}
