// Generated by PayloadTemplates.cloudflarePayload — regenerate, do not edit
import type { Metadata } from 'next'
import { documentOf } from './site'

export const dynamic = 'force-dynamic'

export async function generateMetadata(): Promise<Metadata> {
  const doc = await documentOf('index')
  return { title: doc.title, description: doc.description, openGraph: { title: doc.title, description: doc.description, type: 'article' } }
}

export default async function Page() {
  const doc = await documentOf('index')
  return <article dangerouslySetInnerHTML={{ __html: doc.html ?? '' }} />
}
