// Generated by PayloadTemplates.cloudflarePayload — regenerate, do not edit
import config from '@payload-config'
import { getPayload } from 'payload'
import { notFound } from 'next/navigation'

export const dynamic = 'force-dynamic'

export const documentOf = async (slug: string) => {
  const payload = await getPayload({ config })
  const found = await payload.find({ collection: 'docs' as never, where: { slug: { equals: slug } }, limit: 1, depth: 0 })
  return (found.docs[0] as { title?: string; description?: string; html?: string } | undefined) ?? notFound()
}
