import { CloudflareCombination, CloudflarePayload, CloudflareApp, cloudflarePayloadOf } from './payload-cloudflare.js'
export { CLOUDFLARE_RUNTIMES, CLOUDFLARE_DATABASES, CLOUDFLARE_STORAGE, CLOUDFLARE_EMAIL, CLOUDFLARE_PLUGINS, CloudflareCombination, CloudflarePayload, cloudflareKeyOf, cloudflareCombinationOf, CloudflareApp, cloudflarePayloadOf, cloudflareCombinations } from './payload-cloudflare.js'
/**
 * Payload Templates for 4-Mode Deployment
 * Browser / Standalone / Docker / Kubernetes
 * Each mode fully specified, formula-derived, zero-config
 */

export interface PayloadTemplate {
  mode: 'browser' | 'standalone' | 'docker' | 'kubernetes' | 'cloudflare'
  version: string
  spec: Record<string, unknown>
  hardware: HardwareTarget
  optimization: OptimizationConfig
  deployment: DeploymentConfig
}

export interface HardwareTarget {
  cpu: { cores: number; freq: number; cache: string }
  memory: { gb: number; type: string }
  network: { bw: string; latency: string }
  storage: { ssd: string; type: string }
  accelerators?: string[]
}

export interface OptimizationConfig {
  cpu: { ipc: number; frequency: number; powerGating: boolean }
  memory: { prefetch: boolean; compression: number; cacheSize: number }
  network: { routing: string; linkGating: boolean }
  power: { vrm: number; thermalTarget: number }
}

export interface DeploymentConfig {
  instances: number
  scaling: { min: number; max: number; target: number }
  monitoring: boolean
  selfHealing: boolean
  autonomousOptimization: boolean
}

/** What an image of the unit is made of, read from package.json and the unit rather than written into a template:
 *  the package (name, version, licence, author, repository), the Node line its engines field names, the port the boot
 *  listens on and the flags the boot answers (--health for the container, --prove for the boot's own receipt). */
export type ImageApp = {
  name: string
  version: string
  license: string
  author: string
  repository: string
  homepage: string
  node: number
  port: number
  boot: string
  health: string
  prove: string
  /** files the image carries beside dist and node_modules */
  ship: string[]
  /** the registry path an orchestrator pulls (ghcr.io/uuidna/qpu) */
  image: string
}

const IMAGE_DEFAULT: ImageApp = {
  name: '@uuidna/qpu', version: '1.0.0', license: 'CC-BY-NC-ND-4.0', author: 'Tsvetan Rouschev', repository: 'https://github.com/uuidna/qpu',
  homepage: 'https://qpu.uuidna.com', node: 26, port: 8787, boot: 'dist/quantum/processing/unit/boot.js', health: '--health', prove: '--prove',
  ship: ['LICENSE', 'README.md', 'CITATION.cff', 'mcp.json', 'install.json'], image: 'ghcr.io/uuidna/qpu',
}

/** The Dockerfile: a build stage that compiles (the version lock is the repository's gate, git and npm being outside the
 *  image), a runtime stage with only dist, production modules and what the package ships, run as its own user behind
 *  dumb-init at the path Alpine installs it, health being the boot's own answer. */
export const dockerfileOf = (a: ImageApp = IMAGE_DEFAULT): string => `# Generated by PayloadTemplates.dockerPayload from package.json and the unit — regenerate, do not edit
# Builds on arm64 and amd64: docker buildx build --platform linux/arm64,linux/amd64 -t ${a.image}:${a.version} .

FROM node:${a.node}-alpine AS build
WORKDIR /qpu
RUN apk add --no-cache python3 make g++
COPY package.json package-lock.json ./
# no lifecycle scripts: prepare would compile before src/ is copied, and the compile step follows
RUN npm ci --ignore-scripts
COPY tsconfig.json ./
COPY src/ ./src/
# compile only: the version lock (git history, npm registry) gates every commit and CI run
RUN npx tsc -p tsconfig.json && npm prune --omit=dev

FROM node:${a.node}-alpine
WORKDIR /qpu
ENV NODE_ENV=production PORT=${a.port}
RUN apk add --no-cache ca-certificates dumb-init
COPY --from=build /qpu/package.json /qpu/package-lock.json ./
COPY --from=build /qpu/dist ./dist
COPY --from=build /qpu/node_modules ./node_modules
COPY ${a.ship.join(' ')} ./
COPY src/quantum/processing/unit/index.lean ./src/quantum/processing/unit/
RUN addgroup -g 1001 -S qpu && adduser -S qpu -u 1001
USER qpu
EXPOSE ${a.port}
HEALTHCHECK --interval=60s --timeout=30s --start-period=10s --retries=3 CMD node ${a.boot} ${a.health} || exit 1
# Alpine installs dumb-init under /usr/bin
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node", "${a.boot}"]

LABEL org.opencontainers.image.title="${a.name}" \
      org.opencontainers.image.version="${a.version}" \
      org.opencontainers.image.authors="${a.author}" \
      org.opencontainers.image.url="${a.homepage}" \
      org.opencontainers.image.source="${a.repository}" \
      org.opencontainers.image.licenses="${a.license}" \
      org.opencontainers.image.base.name="docker.io/library/node:${a.node}-alpine"
`

/** docker-compose: the one service, built from the Dockerfile beside it, its port published as the boot listens. */
export const composeOf = (a: ImageApp = IMAGE_DEFAULT): string => `# Generated by PayloadTemplates.dockerPayload from package.json and the unit — regenerate, do not edit
services:
  qpu:
    build: .
    image: ${a.image}:${a.version}
    ports:
      - "${a.port}:${a.port}"
    environment:
      NODE_ENV: production
      PORT: "${a.port}"
    healthcheck:
      test: ["CMD", "node", "${a.boot}", "${a.health}"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 10s
    restart: unless-stopped
`

/** Kubernetes: namespace, service account, deployment, service and autoscaler in one manifest, every port the boot's,
 *  every probe the boot's own answer, the replicas and bounds from the template's deployment config. */
export const kubernetesOf = (a: ImageApp = IMAGE_DEFAULT, d: DeploymentConfig = { instances: 3, scaling: { min: 2, max: 20, target: 70 }, monitoring: true, selfHealing: true, autonomousOptimization: false }): string => `# Generated by PayloadTemplates.kubernetesPayload from package.json and the unit — regenerate, do not edit
# kubectl apply -f k8s/qpu.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: qpu
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qpu
  namespace: qpu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qpu
  namespace: qpu
  labels: { app: qpu, version: "${a.version}" }
spec:
  replicas: ${d.instances}
  selector:
    matchLabels: { app: qpu }
  template:
    metadata:
      labels: { app: qpu, version: "${a.version}" }
    spec:
      serviceAccountName: qpu
      securityContext: { runAsNonRoot: true, runAsUser: 1001 }
      containers:
        - name: qpu
          image: ${a.image}:${a.version}
          ports:
            - { name: http, containerPort: ${a.port} }
          env:
            - { name: NODE_ENV, value: production }
            - { name: PORT, value: "${a.port}" }
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests: { cpu: 250m, memory: 256Mi }
            limits: { cpu: "1", memory: 512Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: qpu
  namespace: qpu
spec:
  selector: { app: qpu }
  ports:
    - { name: http, port: 80, targetPort: http }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qpu
  namespace: qpu
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: qpu }
  minReplicas: ${d.scaling.min}
  maxReplicas: ${d.scaling.max}
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: ${d.scaling.target} } }
`

/**
 * Deployment templates: four hardware modes (browser, standalone, docker, kubernetes) and the Cloudflare family (cloudflarePayload) for Next.js + Payload on Workers.
 * @wing cms
 * @kind class
 */
export class PayloadTemplates {
  /**
   * BROWSER MODE: In-app execution via WebAssembly
   * Minimal footprint, real-time UI updates, no backend required
   */
  static browserPayload(): PayloadTemplate {
    return {
      mode: 'browser',
      version: '1.0.0',
      spec: {
        runtime: 'wasm',
        bundle: {
          core: 'uuid-mcp-core.wasm',
          quantum: 'quantum-secure-signalling.wasm',
          formulas: 'cross-domain-formulas.wasm',
          hardware: 'hardware-optimization-manifesto.wasm'
        },
        modules: 65, // all MCP operations
        domains: 12, // all connected domains
        size: '4.2MB', // gzipped
        initTime: '120ms',
        memoryLimit: '256MB'
      },
      hardware: {
        cpu: { cores: 2, freq: 2400, cache: '8MB' },
        memory: { gb: 4, type: 'shared' },
        network: { bw: '10Mbps', latency: '50ms' },
        storage: { ssd: '1GB', type: 'indexeddb' }
      },
      optimization: {
        cpu: { ipc: 1.2, frequency: 1800, powerGating: false },
        memory: { prefetch: true, compression: 0.65, cacheSize: 128 },
        network: { routing: 'direct', linkGating: false },
        power: { vrm: 0.8, thermalTarget: 65 }
      },
      deployment: {
        instances: 1,
        scaling: { min: 1, max: 1, target: 1 },
        monitoring: true,
        selfHealing: true,
        autonomousOptimization: true
      }
    }
  }

  /**
   * STANDALONE MODE: Desktop/CLI application
   * Full performance, all optimizations enabled, system integration
   */
  static standalonePayload(): PayloadTemplate {
    return {
      mode: 'standalone',
      version: '1.0.0',
      spec: {
        runtime: 'node.js/v20+',
        binary: 'qpu-standalone',
        entrypoint: 'dist/standalone-server.js',
        modules: 65,
        domains: 12,
        size: '15.3MB', // uncompressed
        initTime: '45ms',
        memoryLimit: '2GB'
      },
      hardware: {
        cpu: { cores: 4, freq: 3600, cache: '16MB' },
        memory: { gb: 8, type: 'local' },
        network: { bw: '1Gbps', latency: '1ms' },
        storage: { ssd: '10GB', type: 'local-filesystem' }
      },
      optimization: {
        cpu: { ipc: 1.54, frequency: 3200, powerGating: true },
        memory: { prefetch: true, compression: 0.58, cacheSize: 512 },
        network: { routing: 'optimized', linkGating: true },
        power: { vrm: 0.68, thermalTarget: 75 }
      },
      deployment: {
        instances: 1,
        scaling: { min: 1, max: 4, target: 2 },
        monitoring: true,
        selfHealing: true,
        autonomousOptimization: true
      }
    }
  }

  /**
   * DOCKER MODE: Container deployment
   * Portable, reproducible, easy horizontal scaling
   */
  static dockerPayload(app: ImageApp = IMAGE_DEFAULT): PayloadTemplate & { files: Record<string, string> } {
    const deployment: DeploymentConfig = { instances: 3, scaling: { min: 1, max: 10, target: 3 }, monitoring: true, selfHealing: true, autonomousOptimization: true }
    return {
      mode: 'docker',
      version: app.version,
      spec: { image: `${app.image}:${app.version}`, dockerfile: dockerfileOf(app), port: app.port, node: app.node, memoryLimit: '4GB' },
      files: { Dockerfile: dockerfileOf(app), 'docker-compose.yml': composeOf(app) },
      hardware: {
        cpu: { cores: 2, freq: 2400, cache: '8MB' },
        memory: { gb: 4, type: 'container' },
        network: { bw: '100Mbps', latency: '5ms' },
        storage: { ssd: '20GB', type: 'volume' }
      },
      optimization: {
        cpu: { ipc: 1.52, frequency: 2200, powerGating: true },
        memory: { prefetch: true, compression: 0.61, cacheSize: 256 },
        network: { routing: 'container-aware', linkGating: true },
        power: { vrm: 0.65, thermalTarget: 70 }
      },
      deployment,
    }
  }

  /**
   * KUBERNETES MODE: Cloud-native orchestration
   * Auto-scaling, resilience, multi-datacenter distribution
   */
  static kubernetesPayload(app: ImageApp = IMAGE_DEFAULT): PayloadTemplate & { files: Record<string, string> } {
    const deployment: DeploymentConfig = { instances: 3, scaling: { min: 2, max: 20, target: 70 }, monitoring: true, selfHealing: true, autonomousOptimization: true }
    return {
      mode: 'kubernetes',
      version: app.version,
      spec: { image: `${app.image}:${app.version}`, namespace: 'qpu', port: app.port, manifest: kubernetesOf(app, deployment), initTime: '2000ms' },
      files: { 'k8s/qpu.yaml': kubernetesOf(app, deployment) },
      hardware: {
        cpu: { cores: 4, freq: 2800, cache: '16MB' },
        memory: { gb: 8, type: 'pod' },
        network: { bw: '1Gbps', latency: '2ms' },
        storage: { ssd: '50GB', type: 'pvc' }
      },
      optimization: {
        cpu: { ipc: 1.6, frequency: 2600, powerGating: true },
        memory: { prefetch: true, compression: 0.58, cacheSize: 512 },
        network: { routing: 'cluster-aware', linkGating: true },
        power: { vrm: 0.7, thermalTarget: 75 }
      },
      deployment,
    }
  }

  /**
   * Generate optimized payload for detected hardware
   */
  static autoDetectPayload(hwProfile: Partial<HardwareTarget>): PayloadTemplate {
    const cores = hwProfile.cpu?.cores || 4
    const memGb = hwProfile.memory?.gb || 8
    const isSSD = hwProfile.storage?.ssd === 'yes'

    // Formula: if cores < 2, use browser; if cores < 8, standalone; if cores < 32, docker; else k8s
    if (cores < 2) return this.browserPayload()
    if (cores < 8) return this.standalonePayload()
    if (cores < 32) return this.dockerPayload()
    return this.kubernetesPayload()
  }

  /**
   * Template validation against hardware constraints
   */
  static validate(payload: PayloadTemplate, hardware: HardwareTarget): { valid: boolean; issues: string[] } {
    const issues: string[] = []

    // CPU: template core requirement vs available cores
    const templateCores = ((payload.spec as Record<string, unknown>).modules as number) || 1
    if (hardware.cpu.cores < Math.ceil((templateCores as number) / 13)) {
      issues.push(`CPU cores (${hardware.cpu.cores}) insufficient for template requirements`)
    }

    // Memory: check allocation
    const memNeeded = payload.optimization.memory.cacheSize / 1024 + 0.5
    if (hardware.memory.gb < memNeeded) {
      issues.push(`Memory (${hardware.memory.gb}GB) insufficient, need ${memNeeded}GB`)
    }

    // Network: latency check
    const maxLatency = payload.mode === 'browser' ? 50 : payload.mode === 'standalone' ? 1 : 5
    const latencyMs = parseInt(hardware.network.latency)
    if (latencyMs > maxLatency) {
      issues.push(`Network latency (${latencyMs}ms) exceeds limit (${maxLatency}ms)`)
    }

    return {
      valid: issues.length === 0,
      issues
    }
  }

  /**
   * All templates indexed by mode
   */
  /** Next.js + Payload on Cloudflare Workers for one combination; enumerate them with cloudflareCombinations(). */
  static cloudflarePayload(c: CloudflareCombination, name?: string, app?: CloudflareApp): CloudflarePayload {
    return cloudflarePayloadOf(c, name, app)
  }

  static allTemplates(): Record<string, PayloadTemplate> {
    return {
      browser: this.browserPayload(),
      standalone: this.standalonePayload(),
      docker: this.dockerPayload(),
      kubernetes: this.kubernetesPayload()
    }
  }
}

// ============================================================================
// CLOUDFLARE: Next.js + Payload on Workers, every combination
// ============================================================================

/**
 * A PayloadTemplates instance.
 * @wing cms
 * @kind function
 */
export const payloadTemplates = new PayloadTemplates()
