// Generated by PayloadTemplates.cloudflarePayload — regenerate, do not edit
import type { Metadata } from 'next'
import { documentOf } from '../../site'

export const dynamic = 'force-dynamic'
type Props = { params: Promise<{ slug: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const doc = await documentOf((await params).slug)
  return { title: doc.title, description: doc.description, openGraph: { title: doc.title, description: doc.description, type: 'article' } }
}

export default async function Page({ params }: Props) {
  const doc = await documentOf((await params).slug)
  return <article dangerouslySetInnerHTML={{ __html: doc.html ?? '' }} />
}
