# Generated by PayloadTemplates.dockerPayload from package.json and the unit — regenerate, do not edit
# Builds on arm64 and amd64: docker buildx build --platform linux/arm64,linux/amd64 -t ghcr.io/uuidna/qpu:1.0.0 .

FROM node:26-alpine AS build
WORKDIR /qpu
RUN apk add --no-cache python3 make g++
COPY package.json package-lock.json ./
# no lifecycle scripts: prepare would compile before src/ is copied, and the compile step follows
RUN npm ci --ignore-scripts
COPY tsconfig.json ./
COPY src/ ./src/
# compile only: the version lock (git history, npm registry) gates every commit and CI run
RUN npx tsc -p tsconfig.json && npm prune --omit=dev

FROM node:26-alpine
WORKDIR /qpu
ENV NODE_ENV=production PORT=8787
RUN apk add --no-cache ca-certificates dumb-init
COPY --from=build /qpu/package.json /qpu/package-lock.json ./
COPY --from=build /qpu/dist ./dist
COPY --from=build /qpu/node_modules ./node_modules
COPY LICENSE README.md CITATION.cff mcp.json install.json ./
COPY src/quantum/processing/unit/index.lean ./src/quantum/processing/unit/
RUN addgroup -g 1001 -S qpu && adduser -S qpu -u 1001
USER qpu
EXPOSE 8787
HEALTHCHECK --interval=60s --timeout=30s --start-period=10s --retries=3 CMD node dist/quantum/processing/unit/boot.js --health || exit 1
# Alpine installs dumb-init under /usr/bin
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node", "dist/quantum/processing/unit/boot.js"]

LABEL org.opencontainers.image.title="@uuidna/qpu"       org.opencontainers.image.version="1.0.0"       org.opencontainers.image.authors="Tsvetan Rouschev <ceccec@psg.bg>"       org.opencontainers.image.url="https://qpu.uuidna.com"       org.opencontainers.image.source="https://github.com/uuidna/qpu"       org.opencontainers.image.licenses="CC-BY-NC-ND-4.0"       org.opencontainers.image.base.name="docker.io/library/node:26-alpine"
