// Generated by PayloadTemplates.cloudflarePayload — regenerate, do not edit
import { defineCloudflareConfig } from '@opennextjs/cloudflare'

export default { ...defineCloudflareConfig({}), buildCommand: 'npx next build --webpack' }
