// Generated by PayloadTemplates.cloudflarePayload — opennext/qpu-raid/r2/none/search+seo — regenerate, do not edit
/// <reference types="@cloudflare/workers-types" />
import { buildConfig } from 'payload'
import type { CollectionConfig } from 'payload'
import { lexicalEditor } from '@payloadcms/richtext-lexical'
import { getCloudflareContext } from '@opennextjs/cloudflare'
import { qpuAdapter } from '@uuidna/qpu/payload'
import { r2Storage } from '@payloadcms/storage-r2'
import { searchPlugin } from '@payloadcms/plugin-search'
import { seoPlugin } from '@payloadcms/plugin-seo'
import { Users } from './src/payload/collections/users'
import { Docs } from './src/payload/collections/docs'
import { FuseApis } from './src/payload/collections/fuse-apis'
import { FuseFields } from './src/payload/collections/fuse-fields'
import { FuseFormulas } from './src/payload/collections/fuse-formulas'
import { QuantumReceipts } from './src/payload/collections/quantum-receipts'
import { seedDocs } from './src/payload/seeds/docs'
type CloudflareEnv = { STORAGE: KVNamespace; BLOBS: R2Bucket; MEDIA: R2Bucket }
const cf = (process.argv.some((a: string) => /^(generate|migrate)/.test(a)) || process.env.NODE_ENV !== 'production' ? await (await import(/* webpackIgnore: true */ `${'__wrangler'.replaceAll('_', '')}`)).getPlatformProxy({ configPath: 'payload.wrangler.jsonc', remoteBindings: false }) : await getCloudflareContext({ async: true })).env as unknown as CloudflareEnv
const Media: CollectionConfig = { slug: 'media', upload: true, fields: [{ name: 'alt', type: 'text' }] }
export default buildConfig({
  secret: process.env.PAYLOAD_SECRET ?? '',
  editor: lexicalEditor(),
  admin: { user: 'users', meta: { titleSuffix: ' — UUIDNA QPU' } },
  collections: [Users, Docs, FuseApis, FuseFields, FuseFormulas, QuantumReceipts, Media],
  db: qpuAdapter({ env: { STORAGE: cf.STORAGE, BLOBS: cf.BLOBS } as never }),
  storage: [r2Storage({ bucket: cf.MEDIA as never, collections: { media: true } })],
  plugins: [searchPlugin({ collections: ['docs'] }), seoPlugin({ collections: ['docs'] })],
  cors: ['https://qpu.uuidna.com'],
  csrf: ['https://qpu.uuidna.com'],
  typescript: { outputFile: './src/payload/payload-types.ts' },
  onInit: async (payload) => { await seedDocs(payload) },
})
