// Generated by PayloadTemplates.cloudflarePayload — opennext/qpu-raid/r2/none/ecommerce+form-builder+import-export+mcp+multi-tenant+nested-docs+redirects+search+sentry+seo+stripe — regenerate, do not edit
/// <reference types="@cloudflare/workers-types" />
import { install as preload0 } from './src/payload/workers-crypto'
import { buildConfig } from 'payload'
import type { CollectionConfig } from 'payload'
import { lexicalEditor } from '@payloadcms/richtext-lexical'
import { getCloudflareContext } from '@opennextjs/cloudflare'
import { qpuAdapter } from '@uuidna/qpu/payload'
import { r2Storage } from '@payloadcms/storage-r2'
import * as Sentry from '@sentry/nextjs'
import { ecommercePlugin } from '@payloadcms/plugin-ecommerce'
import { formBuilderPlugin } from '@payloadcms/plugin-form-builder'
import { importExportPlugin } from '@payloadcms/plugin-import-export'
import { mcpPlugin } from '@payloadcms/plugin-mcp'
import { multiTenantPlugin } from '@payloadcms/plugin-multi-tenant'
import { nestedDocsPlugin } from '@payloadcms/plugin-nested-docs'
import { redirectsPlugin } from '@payloadcms/plugin-redirects'
import { searchPlugin } from '@payloadcms/plugin-search'
import { sentryPlugin } from '@payloadcms/plugin-sentry'
import { seoPlugin } from '@payloadcms/plugin-seo'
import { stripePlugin } from '@payloadcms/plugin-stripe'
import { Users } from './src/payload/collections/users'
import { Tenants } from './src/payload/collections/tenants'
import { Docs } from './src/payload/collections/docs'
import { FuseApis } from './src/payload/collections/fuse-apis'
import { FuseFields } from './src/payload/collections/fuse-fields'
import { FuseFormulas } from './src/payload/collections/fuse-formulas'
import { QuantumReceipts } from './src/payload/collections/quantum-receipts'
import { seoTitleOf } from './src/payload/collections/docs'
import { seoDescriptionOf } from './src/payload/collections/docs'
import { seoURLOf } from './src/payload/collections/docs'
import { seed } from './src/payload/seeds'
preload0()
type CloudflareEnv = { STORAGE: KVNamespace; BLOBS: R2Bucket; MEDIA: R2Bucket }
const cf = (process.argv.some((a: string) => /^(generate|migrate)/.test(a)) || process.env.NODE_ENV !== 'production' ? await (await import(/* webpackIgnore: true */ `${'__wrangler'.replaceAll('_', '')}`)).getPlatformProxy({ configPath: 'payload.wrangler.jsonc', remoteBindings: false }) : await getCloudflareContext({ async: true })).env as unknown as CloudflareEnv
const Media: CollectionConfig = { slug: 'media', upload: true, fields: [{ name: 'alt', type: 'text' }] }
export default buildConfig({
  secret: process.env.PAYLOAD_SECRET ?? '',
  editor: lexicalEditor(),
  admin: { user: 'users', meta: { titleSuffix: ' — UUIDNA QPU' } },
  collections: [Users, Tenants, Docs, FuseApis, FuseFields, FuseFormulas, QuantumReceipts, Media],
  db: qpuAdapter({ env: { STORAGE: cf.STORAGE, BLOBS: cf.BLOBS } as never }),
  storage: [r2Storage({ bucket: cf.MEDIA as never, collections: { media: true } })],
  plugins: [ecommercePlugin({ customers: { slug: 'users' }, access: { isAdmin: ({ req }) => Boolean(req.user), adminOnlyFieldAccess: ({ req }) => Boolean(req.user), adminOrPublishedStatus: ({ req }) => (req.user ? true : { _status: { equals: 'published' } }), isDocumentOwner: ({ req }) => (req.user ? { customer: { equals: req.user.id } } : false) }, products: { productsCollectionOverride: ({ defaultCollection }) => ({ ...defaultCollection, admin: { ...defaultCollection.admin, useAsTitle: 'title' }, fields: [{ name: 'title', type: 'text', required: true }, { name: 'slug', type: 'text', unique: true, index: true }, { name: 'description', type: 'textarea' }, ...defaultCollection.fields] }) } }), formBuilderPlugin({}), importExportPlugin({ collections: [{ slug: 'docs' }, { slug: 'quantum-receipts' }, { slug: 'fuse-apis' }, { slug: 'fuse-fields' }, { slug: 'fuse-formulas' }] }), mcpPlugin({ collections: { 'docs': { description: 'docs' }, 'quantum-receipts': { description: 'quantum-receipts' }, 'fuse-formulas': { description: 'fuse-formulas' } } }), multiTenantPlugin({ collections: {  }, tenantsArrayField: { includeDefaultField: false }, userHasAccessToAllTenants: (user) => (user as { role?: string } | null)?.role === 'super-admin' }), nestedDocsPlugin({ collections: ['docs'] }), redirectsPlugin({ collections: ['docs'] }), searchPlugin({ collections: ['docs'] }), sentryPlugin({ Sentry, enabled: Boolean(process.env.SENTRY_DSN) }), seoPlugin({ collections: ['docs'], uploadsCollection: 'media', generateTitle: ({ doc }) => seoTitleOf(doc), generateDescription: ({ doc }) => seoDescriptionOf(doc), generateURL: ({ doc }) => seoURLOf(doc) }), stripePlugin({ stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? '' })],
  cors: ['https://qpu.uuidna.com'],
  csrf: ['https://qpu.uuidna.com'],
  typescript: { outputFile: './src/payload/payload-types.ts' },
  onInit: async (payload) => { await seed(payload) },
})
