// Generated by PayloadTemplates.cloudflarePayload — vinext/qpu-raid/none/none/- — regenerate, do not edit
/// <reference types="@cloudflare/workers-types" />
import { buildConfig } from 'payload'
import type { CollectionConfig } from 'payload'
import { lexicalEditor } from '@payloadcms/richtext-lexical'
import { env } from 'cloudflare:workers'
import { qpuAdapter } from '@uuidna/qpu/payload'
import { Users } from './src/payload/collections/users'
import { ComplianceIssues } from './src/payload/collections/compliance-issues'
import { AuditLogs } from './src/payload/collections/audit-logs'
import { SupportTickets } from './src/payload/collections/support-tickets'
import { Enrollments } from './src/payload/collections/enrollments'
import { Metrics } from './src/payload/collections/metrics'
import { Certifications } from './src/payload/collections/certifications'
import { FuseApis } from './src/payload/collections/fuse-apis'
import { FuseFields } from './src/payload/collections/fuse-fields'
import { FuseFormulas } from './src/payload/collections/fuse-formulas'
import { QuantumReceipts } from './src/payload/collections/quantum-receipts'
type CloudflareEnv = { STORAGE: KVNamespace; BLOBS: R2Bucket }
const cf = env as unknown as CloudflareEnv
export default buildConfig({
  secret: process.env.PAYLOAD_SECRET ?? '',
  editor: lexicalEditor(),
  admin: { user: 'users' },
  collections: [Users, ComplianceIssues, AuditLogs, SupportTickets, Enrollments, Metrics, Certifications, FuseApis, FuseFields, FuseFormulas, QuantumReceipts],
  db: qpuAdapter({ env: { STORAGE: cf.STORAGE, BLOBS: cf.BLOBS } as never }),
  plugins: [],
  typescript: { outputFile: './src/payload/payload-types.ts' },
})
