// Generated by PayloadTemplates.cloudflarePayload — vinext/qpu-raid/r2/resend/nested-docs+search — regenerate, do not edit
/// <reference types="@cloudflare/workers-types" />
import { buildConfig } from 'payload'
import type { CollectionConfig } from 'payload'
import { lexicalEditor } from '@payloadcms/richtext-lexical'
import { env } from 'cloudflare:workers'
import { qpuAdapter } from '@uuidna/qpu/payload'
import { r2Storage } from '@payloadcms/storage-r2'
import { resendAdapter } from '@payloadcms/email-resend'
import { nestedDocsPlugin } from '@payloadcms/plugin-nested-docs'
import { searchPlugin } from '@payloadcms/plugin-search'
import { Users } from './src/payload/collections/users'
import { ComplianceIssues } from './src/payload/collections/compliance-issues'
import { AuditLogs } from './src/payload/collections/audit-logs'
import { SupportTickets } from './src/payload/collections/support-tickets'
import { Enrollments } from './src/payload/collections/enrollments'
import { Metrics } from './src/payload/collections/metrics'
import { Certifications } from './src/payload/collections/certifications'
import { FuseApis } from './src/payload/collections/fuse-apis'
import { FuseFields } from './src/payload/collections/fuse-fields'
import { FuseFormulas } from './src/payload/collections/fuse-formulas'
import { QuantumReceipts } from './src/payload/collections/quantum-receipts'
type CloudflareEnv = { STORAGE: KVNamespace; BLOBS: R2Bucket; MEDIA: R2Bucket }
const cf = env as unknown as CloudflareEnv
const Media: CollectionConfig = { slug: 'media', upload: true, fields: [{ name: 'alt', type: 'text' }] }
export default buildConfig({
  secret: process.env.PAYLOAD_SECRET ?? '',
  editor: lexicalEditor(),
  admin: { user: 'users', meta: { titleSuffix: ' — UUIDNA QPU' }, components: { views: { dashboard: { Component: '/src/payload/admin/dashboards/index#AdminDashboard' } } } },
  collections: [Users, ComplianceIssues, AuditLogs, SupportTickets, Enrollments, Metrics, Certifications, FuseApis, FuseFields, FuseFormulas, QuantumReceipts, Media],
  db: qpuAdapter({ env: { STORAGE: cf.STORAGE, BLOBS: cf.BLOBS } as never }),
  email: resendAdapter({ apiKey: process.env.RESEND_API_KEY ?? '', defaultFromAddress: process.env.EMAIL_FROM ?? 'noreply@example.com', defaultFromName: 'Payload' }),
  storage: [r2Storage({ bucket: cf.MEDIA as never, collections: { media: true } })],
  plugins: [nestedDocsPlugin({ collections: ['certifications', 'enrollments'] }), searchPlugin({ collections: ['compliance-issues', 'support-tickets', 'audit-logs', 'enrollments', 'metrics'] })],
  cors: ['http://localhost:3000','http://localhost:3001','https://qpu.uuidna.com'],
  csrf: ['http://localhost:3000','http://localhost:3001','https://qpu.uuidna.com'],
  typescript: { outputFile: './src/payload/payload-types.ts' },
})
