// Seed data for Metrics collection - extracted from enterprise.test.ts and MetricsFlow.tsx
export const metricsSeed = [
  {
    name: 'CPU Usage',
    category: 'system',
    value: 45,
    unit: '%',
    status: 'healthy',
    timestamp: new Date('2024-01-20T11:00:00Z'),
    threshold: 80,
    trend: 'stable',
    source: 'operations-dashboard',
  },
  {
    name: 'Memory Usage',
    category: 'system',
    value: 60,
    unit: '%',
    status: 'healthy',
    timestamp: new Date('2024-01-20T11:00:00Z'),
    threshold: 85,
    trend: 'up',
    source: 'operations-dashboard',
  },
  {
    name: 'Learning',
    category: 'business',
    value: 89.7,
    unit: '%',
    status: 'healthy',
    timestamp: new Date('2024-01-20T11:00:00Z'),
    threshold: 70,
    trend: 'up',
    source: 'metrics-flow',
  },
  {
    name: 'Robustness',
    category: 'reliability',
    value: 94.2,
    unit: '%',
    status: 'healthy',
    timestamp: new Date('2024-01-20T11:00:00Z'),
    threshold: 90,
    trend: 'stable',
    source: 'metrics-flow',
  },
  {
    name: 'Efficiency',
    category: 'performance',
    value: 78.0,
    unit: '%',
    status: 'healthy',
    timestamp: new Date('2024-01-20T11:00:00Z'),
    threshold: 75,
    trend: 'up',
    source: 'metrics-flow',
  },
  {
    name: 'Collaboration',
    category: 'business',
    value: 79.5,
    unit: '%',
    status: 'healthy',
    timestamp: new Date('2024-01-20T11:00:00Z'),
    threshold: 70,
    trend: 'stable',
    source: 'metrics-flow',
  },
  {
    name: 'API Latency',
    category: 'performance',
    value: 250,
    unit: 'ms',
    status: 'healthy',
    timestamp: new Date('2024-01-20T11:00:00Z'),
    threshold: 500,
    trend: 'down',
    source: 'performance-benchmarker',
  },
  {
    name: 'Error Rate',
    category: 'reliability',
    value: 0.5,
    unit: '%',
    status: 'healthy',
    timestamp: new Date('2024-01-20T11:00:00Z'),
    threshold: 1,
    trend: 'down',
    source: 'monitoring-setup',
  },
]
