// Generated by PayloadTemplates.cloudflarePayload from the folders beside this file — regenerate, do not edit
import { Apps } from './Apps/index.js'
import { Banner } from './Banner/index.js'
import { BlogContent } from './BlogContent/index.js'
import { BlogMarkdown } from './BlogMarkdown/index.js'
import { Bodygraph } from './Bodygraph/index.js'
import { CallToAction } from './CallToAction/index.js'
import { Callout } from './Callout/index.js'
import { CardGrid } from './CardGrid/index.js'
import { CaseStudiesHighlight } from './CaseStudiesHighlight/index.js'
import { CaseStudyCards } from './CaseStudyCards/index.js'
import { CaseStudyParallax } from './CaseStudyParallax/index.js'
import { Clay } from './Clay/index.js'
import { Code } from './Code/index.js'
import { CodeFeature } from './CodeFeature/index.js'
import { ComparisonTable } from './ComparisonTable/index.js'
import { Content } from './Content/index.js'
import { ContentGrid } from './ContentGrid/index.js'
import { Discovery } from './Discovery/index.js'
import { Docs } from './Docs/index.js'
import { Download } from './Download/index.js'
import { ExampleTabs } from './ExampleTabs/index.js'
import { Families } from './Families/index.js'
import { Form } from './Form/index.js'
import { Hero } from './Hero/index.js'
import { HoverCards } from './HoverCards/index.js'
import { HoverHighlights } from './HoverHighlights/index.js'
import { LinkGrid } from './LinkGrid/index.js'
import { Live } from './Live/index.js'
import { LogoGrid } from './LogoGrid/index.js'
import { Media } from './Media/index.js'
import { MediaContent } from './MediaContent/index.js'
import { MediaContentAccordion } from './MediaContentAccordion/index.js'
import { Pricing } from './Pricing/index.js'
import { Products } from './Products/index.js'
import { Program } from './Program/index.js'
import { Receipt } from './Receipt/index.js'
import { Receipts } from './Receipts/index.js'
import { ReusableContent } from './ReusableContent/index.js'
import { Search } from './Search/index.js'
import { Slider } from './Slider/index.js'
import { Statement } from './Statement/index.js'
import { Stats } from './Stats/index.js'
import { Steps } from './Steps/index.js'
import { StickyHighlights } from './StickyHighlights/index.js'
import { Wings } from './Wings/index.js'

export const blockComponents = {
  apps: Apps,
  banner: Banner,
  blogContent: BlogContent,
  blogMarkdown: BlogMarkdown,
  bodygraph: Bodygraph,
  callToAction: CallToAction,
  callout: Callout,
  cardGrid: CardGrid,
  caseStudiesHighlight: CaseStudiesHighlight,
  caseStudyCards: CaseStudyCards,
  caseStudyParallax: CaseStudyParallax,
  clay: Clay,
  code: Code,
  codeFeature: CodeFeature,
  comparisonTable: ComparisonTable,
  content: Content,
  contentGrid: ContentGrid,
  discovery: Discovery,
  docs: Docs,
  download: Download,
  exampleTabs: ExampleTabs,
  families: Families,
  form: Form,
  hero: Hero,
  hoverCards: HoverCards,
  hoverHighlights: HoverHighlights,
  linkGrid: LinkGrid,
  live: Live,
  logoGrid: LogoGrid,
  media: Media,
  mediaContent: MediaContent,
  mediaContentAccordion: MediaContentAccordion,
  pricing: Pricing,
  products: Products,
  program: Program,
  receipt: Receipt,
  receipts: Receipts,
  reusableContent: ReusableContent,
  search: Search,
  slider: Slider,
  statement: Statement,
  stats: Stats,
  steps: Steps,
  stickyHighlights: StickyHighlights,
  wings: Wings,
}
