// Generated by PayloadTemplates.cloudflarePayload from the folders beside this file — regenerate, do not edit
import { Animation } from './Animation'
import { Bodygraph } from './Bodygraph'
import { CallToAction } from './CallToAction'
import { Clay } from './Clay'
import { Content } from './Content'
import { Discovery } from './Discovery'
import { Docs } from './Docs'
import { Families } from './Families'
import { Form } from './Form'
import { Hero } from './Hero'
import { Live } from './Live'
import { Products } from './Products'
import { Program } from './Program'
import { Receipt } from './Receipt'
import { Receipts } from './Receipts'
import { Search } from './Search'
import { Stats } from './Stats'
import { Uses } from './Uses'
import { Wings } from './Wings'

export const blockComponents = {
  animation: Animation,
  bodygraph: Bodygraph,
  callToAction: CallToAction,
  clay: Clay,
  content: Content,
  discovery: Discovery,
  docs: Docs,
  families: Families,
  form: Form,
  hero: Hero,
  live: Live,
  products: Products,
  program: Program,
  receipt: Receipt,
  receipts: Receipts,
  search: Search,
  stats: Stats,
  uses: Uses,
  wings: Wings,
}
