// lean.test — THE PROOF IS SERVED, NOT CITED. The Lean file the unit names as its source is embedded and served at that
// path; this test compares the served bytes to the file on disk (the embed is generated by hand, never by the build,
// so a stale embed fails here), folds them, and checks every served theorem string appears in the source verbatim.
import { test } from './receipted.js'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import worker, { mintOf, qpuFoldOf, qpuLeanOf, qpuLeanSourceOf, qpuProveOf, qpuProveHolds, qpuQuantumOf, qpuShorOf } from './index.js'
import { leanPath, leanSource, leanToolchain } from './lean.js'
import { packageVersion } from './version.js'

const host = 'qpu.uuidna.com'
const env = { QPU_HOST: host }
const origin = `https://${host}`
const onDisk = () => readFileSync(join(process.cwd(), 'src/quantum/processing/unit/index.lean'), 'utf8')

test('the embedded Lean source is the file on disk, byte for byte, and GET serves it as text', async () => {
  assert.equal(leanPath, 'src/quantum/processing/unit/index.lean')
  assert.equal(leanSource, onDisk())
  assert.equal(leanToolchain, readFileSync(join(process.cwd(), 'lean-toolchain'), 'utf8').trim())
  // the served version is package.json's, embedded by hand like the proof; a stale embed fails here, never repairs itself
  assert.equal(packageVersion, (JSON.parse(readFileSync(join(process.cwd(), 'package.json'), 'utf8')) as { version: string }).version)
  const res = await worker.fetch(new Request(`${origin}/src/quantum/processing/unit/index.lean`), env)
  assert.equal(res.status, 200)
  assert.equal(res.headers.get('content-type'), 'text/plain; charset=utf-8')
  assert.equal(res.headers.get('access-control-allow-origin'), '*')
  const body = await res.text()
  assert.equal(body, onDisk())
  assert.equal(body.startsWith('def mintOf : Nat'), true)
  const wrong = await worker.fetch(new Request(`${origin}/src/quantum/processing/unit/index.ts`), env)
  assert.notEqual(wrong.status, 200)
})

test('the lean dataset folds its source and every served theorem is in it verbatim', () => {
  const lean = qpuLeanOf()
  assert.equal(lean.source.href, `${origin}/src/quantum/processing/unit/index.lean`)
  assert.equal(lean.source.fold, qpuFoldOf(onDisk()))
  assert.equal(lean.source.bytes, Buffer.byteLength(onDisk(), 'utf8'))
  assert.equal(lean.source.verbatim, lean.source.served)
  assert.equal(lean.source.served, lean.rows.length + lean.cover.length + 1)
  assert.equal(lean.source.theorems >= lean.source.served, true)
  assert.equal(lean.source.check, 'lean src/quantum/processing/unit/index.lean')
  assert.equal(lean.source.holds, true)
  // mutation arm: a theorem string the file does not contain is counted as missing, and holds falls
  const forged = { heading: 'forged', theorem: 'theorem forged : 1 = 2 := rfl', formula: '\\mathrm{one}=2', reading: 'never', holds: true }
  const bent = qpuLeanSourceOf([...lean.rows, forged], lean.cover, lean.climb)
  assert.equal(bent.verbatim, bent.served - 1)
  assert.equal(bent.holds, false)
})

test('qpu_prove carries the source fold and the receipts of its own Shor run', () => {
  const prove = qpuProveOf()
  assert.equal(qpuProveHolds(prove), true)
  assert.equal(prove.source.fold, qpuFoldOf(leanSource))
  assert.equal(prove.receipts.holds, true)
  assert.equal(prove.receipts.rows.some((r) => r.name === 'cmodexp' && r.dim === 512 && r.fold.length === 16), true)
  assert.equal(prove.receipts.rows.some((r) => r.name === 'xx' && r.dim === 512), true)
  const again = qpuProveOf()
  assert.equal(again.receipts.fold, prove.receipts.fold)
})

// THE KERNEL MUST NOT ALREADY KNOW THE ANSWER. theorem shor computes its own period and factors; the statement may
// carry only the instance (8, 91) and the small constants of the arithmetic, never 7, 13, or 4. And the file stays
// sorry-free, axiom-free, and decide-free, so every proof is a term the kernel reduced.
test('index.lean is sorry-free, axiom-free, decide-free, and theorem shor carries no answer', () => {
  assert.equal(/\bsorry\b/.test(leanSource), false)
  assert.equal(/^axiom\b/m.test(leanSource), false)
  assert.equal(leanSource.includes('by decide'), false)
  assert.equal(leanSource.includes('native_decide'), false)
  const line = leanSource.split('\n').find((l) => l.startsWith('theorem shor :'))
  assert.ok(line)
  const statement = line.slice(0, line.indexOf(':='))
  for (const fn of ['periodOf', 'half', 'gcdOf']) {
    assert.ok(statement.includes(fn), fn)
    assert.ok(leanSource.split('\n').some((l) => l.startsWith(`def ${fn} `)), `def ${fn}`)
  }
  const numerals = [...new Set(statement.match(/\d+/g) ?? [])].sort()
  assert.deepEqual(numerals, ['0', '1', '2', '8', '91'])
  const shor = qpuShorOf()
  assert.equal(shor.factors.p * shor.factors.q, shor.n)
  assert.equal(numerals.includes(String(shor.factors.p)), false)
  assert.equal(numerals.includes(String(shor.factors.q)), false)
  assert.equal(numerals.includes(String(shor.post.period)), false)
})

test('each Lean identity has exactly one mirror here, and the crossing says which domains rest on it', () => {
  // A CROSS FORMULA EXPLAINS A CROSS-DOMAIN PROBLEM, and it can only do that if there is one of it.
  //
  // Six identities from index.lean were restated inline about sixty-six times across the unit — `faces = coins *
  // rays` nine times, `next = fused + fused` eighteen, `coil = faces` fifteen — each under a different receiver
  // and none of them naming the theorem. That is not merely repetition. It hides the crossing: when the same
  // identity is load-bearing in Alpine and in Capacity and in Circuit, a fault in one predicts a fault in the
  // others, and sixty-six anonymous copies make that impossible to see or to act on.
  //
  // So the mirrors are checked against the live lattice, and the crossing is computed from the source.
  const lean = readFileSync(join(process.cwd(), 'src', 'quantum', 'processing', 'unit', 'index.lean'), 'utf8')
  const source = readFileSync(join(process.cwd(), 'src', 'quantum', 'processing', 'unit', 'index.ts'), 'utf8')

  // THE MIRRORS AGREE WITH THE LATTICE THE UNIT ACTUALLY COMPUTES. A mirror is only worth having one of if it is
  // the right one, so each is evaluated against the served quantum rather than against its own definition.
  const quantum = qpuQuantumOf()
  const { faces, rays, coins } = quantum.faces
  const { bits, vertices, hexbit } = quantum.cube
  assert.equal(faces, coins * rays, 'theorem around')
  assert.equal(faces, rays + rays, 'theorem harmonic')
  assert.equal(bits, vertices * hexbit, 'theorem cube')
  assert.equal(quantum.next, quantum.fused + quantum.fused, 'theorem next_fused')

  // …and each is a theorem index.lean actually declares, so the names are Lean's and not ours.
  const declared = new Set([...lean.matchAll(/^theorem (\w+)/gm)].map(([, name]) => name))
  const mirrors = [...source.matchAll(/^  (\w+): \(/gm)].map(([, name]) => name)
  const mirrored = mirrors.filter((name) => declared.has(name))
  assert.equal(mirrored.length, quantum.circuit.register.qubits * quantum.circuit.register.qubits, `${mirrored.length} mirrors carry a Lean theorem's name`)
  for (const name of mirrored) assert.ok(declared.has(name), `${name} is not a theorem index.lean declares`)

  // THE GUARD THAT STOPS THE RESTATEMENTS COMING BACK. Each identity is written out here exactly once — inside
  // its own mirror — and every other site calls it. A second spelling anywhere is the duplication returning.
  const body = source.slice(source.indexOf('const theorem = {'))
  const restatements: Record<string, RegExp> = {
    around: /[\w.]*faces === [\w.]*coins \* [\w.]*rays/g,
    harmonic: /[\w.]*faces === [\w.]*rays \+ [\w.]*rays/g,
    next_fused: /[\w.]*next === [\w.]*fused \+ [\w.]*fused/g,
    cube: /[\w.]*bits === [\w.]*vertices \* [\w.]*hexbit/g,
  }
  for (const [name, shape] of Object.entries(restatements)) {
    const spelled = (body.match(shape) ?? []).length
    assert.equal(spelled, 1, `theorem ${name} is written out ${spelled} times; it belongs in its mirror and nowhere else`)
  }

  // THE CROSSING ITSELF. Every call is attributed to the binding that encloses it — that binding is the domain —
  // so the table says which domains a single identity holds together.
  const lines = source.split('\n')
  const crossing = new Map<string, Set<string>>()
  let domain = '(top level)'
  for (const line of lines) {
    const bound = line.match(/^(?:export )?const (\w+) = /)
    if (bound) domain = bound[1]!
    if (line.trimStart().startsWith('*')) continue
    for (const [, name] of line.matchAll(/\btheorem\.(\w+)\(/g)) {
      if (!declared.has(name)) continue
      if (!crossing.has(name)) crossing.set(name, new Set())
      crossing.get(name)!.add(domain)
    }
  }

  // An identity used in one place is not a cross formula, it is a local check. Each of these crosses at least
  // coins domains, and the count is reported so a reader learns the blast radius rather than only the rule.
  for (const [name, domains] of crossing) {
    assert.ok(domains.size >= coins, `theorem ${name} is load-bearing in only ${domains.size} domain(s)`)
  }
  assert.ok(crossing.size >= coins + coins, `only ${crossing.size} identities are shared across domains`)
  const spread = [...crossing.values()].reduce((all, d) => all + d.size, 0)
  assert.ok(spread >= faces + faces, `the identities cross only ${spread} domains in total`)
})

test('the symmetric and asymmetric readings of each quantity prove one another, and coincide only at coins', () => {
  // index.lean does not state these as two facts. It derives one from the other:
  //
  //   theorem harmonic : faces = rays + rays := by rw [around, coins_two, Nat.two_mul]
  //
  // A symmetric form — a sum of like terms, unchanged by exchanging them — proved FROM an asymmetric one, a
  // product of unlike terms. What carries it across is coins = seed + seed. Asserted over a RANGE below rather
  // than at the lattice's own values, because an identity that holds at 14 and nowhere else is a coincidence,
  // and it is the implication that is being claimed, not the arithmetic of one number.
  const quantum = qpuQuantumOf()
  const { faces, rays, coins } = quantum.faces
  const { bits, vertices, hexbit } = quantum.cube

  // AROUND ⟺ HARMONIC, for every ray count, given coins is a doubling.
  for (let r = 0; r <= faces * faces; r++) {
    const f = coins * r
    assert.equal(f === coins * r, f === r + r, `around and harmonic disagree at rays ${r}`)
  }
  // The bridge is the only reason: at any other coin count the two readings come apart.
  for (const c of [1, 3, 4, 5]) {
    const r = rays
    assert.notEqual(c * r === r + r, true, `a lattice on ${c} coins would not read both ways`)
  }

  // MULTIPLY IS THE GENERAL BRIDGE — a sum inside mintOf is a product outside it — and it is what lets the cube
  // be read additively and multiplicatively as the same 32.
  for (let a = 0; a <= hexbit; a++) {
    for (let b = 0; b <= hexbit; b++) {
      assert.equal(mintOf(a + b), mintOf(a) * mintOf(b), `multiply fails at ${a} + ${b}`)
    }
  }
  assert.equal(bits, vertices * hexbit, 'cube, read as a product')
  assert.equal(bits, mintOf(quantum.circuit.register.qubits + coins), 'cube, read as a sum inside mintOf')

  // AND THEY COINCIDE AT EXACTLY ONE VALUE. x + x, x * x and mintOf x agree only at coins — which is why a
  // lattice built on coins can be read either way, and why tetra and dense both hold while neither generalises.
  const agree: number[] = []
  for (let x = 0; x <= faces; x++) if (x + x === x * x && x + x === mintOf(x)) agree.push(x)
  assert.deepEqual(agree, [coins], `the symmetric and asymmetric readings coincide at ${agree.join(', ')}`)
  // Zero satisfies the sum-product pair but not the mintOf one, so it is excluded above rather than by luck.
  assert.equal(0 + 0 === 0 * 0, true)
  assert.notEqual(0 + 0, mintOf(0))
})
