// lean.test — THE PROOF IS SERVED, NOT CITED. The Lean file the unit names as its source is embedded and served at that
// path; this test compares the served bytes to the file on disk (the embed is generated by hand, never by the build,
// so a stale embed fails here), folds them, and checks every served theorem string appears in the source verbatim.
import { test } from './receipted.js'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import worker, { qpuFoldOf, qpuLeanOf, qpuLeanSourceOf, qpuProveOf, qpuProveHolds, qpuShorOf } from './index.js'
import { leanPath, leanSource, leanToolchain } from './lean.js'

const host = 'qpu.uuidna.com'
const env = { QPU_HOST: host }
const origin = `https://${host}`
const onDisk = () => readFileSync(join(process.cwd(), 'src/quantum/processing/unit/index.lean'), 'utf8')

test('the embedded Lean source is the file on disk, byte for byte, and GET serves it as text', async () => {
  assert.equal(leanPath, 'src/quantum/processing/unit/index.lean')
  assert.equal(leanSource, onDisk())
  assert.equal(leanToolchain, readFileSync(join(process.cwd(), 'lean-toolchain'), 'utf8').trim())
  const res = await worker.fetch(new Request(`${origin}/src/quantum/processing/unit/index.lean`), env)
  assert.equal(res.status, 200)
  assert.equal(res.headers.get('content-type'), 'text/plain; charset=utf-8')
  assert.equal(res.headers.get('access-control-allow-origin'), '*')
  const body = await res.text()
  assert.equal(body, onDisk())
  assert.equal(body.startsWith('def mintOf : Nat'), true)
  const wrong = await worker.fetch(new Request(`${origin}/src/quantum/processing/unit/index.ts`), env)
  assert.notEqual(wrong.status, 200)
})

test('the lean dataset folds its source and every served theorem is in it verbatim', () => {
  const lean = qpuLeanOf()
  assert.equal(lean.source.href, `${origin}/src/quantum/processing/unit/index.lean`)
  assert.equal(lean.source.fold, qpuFoldOf(onDisk()))
  assert.equal(lean.source.bytes, Buffer.byteLength(onDisk(), 'utf8'))
  assert.equal(lean.source.verbatim, lean.source.served)
  assert.equal(lean.source.served, lean.rows.length + lean.cover.length + 1)
  assert.equal(lean.source.theorems >= lean.source.served, true)
  assert.equal(lean.source.check, 'lean src/quantum/processing/unit/index.lean')
  assert.equal(lean.source.holds, true)
  // mutation arm: a theorem string the file does not contain is counted as missing, and holds falls
  const forged = { heading: 'forged', theorem: 'theorem forged : 1 = 2 := rfl', formula: '\\mathrm{one}=2', reading: 'never', holds: true }
  const bent = qpuLeanSourceOf([...lean.rows, forged], lean.cover, lean.climb)
  assert.equal(bent.verbatim, bent.served - 1)
  assert.equal(bent.holds, false)
})

test('qpu_prove carries the source fold and the receipts of its own Shor run', () => {
  const prove = qpuProveOf()
  assert.equal(qpuProveHolds(prove), true)
  assert.equal(prove.source.fold, qpuFoldOf(leanSource))
  assert.equal(prove.receipts.holds, true)
  assert.equal(prove.receipts.rows.some((r) => r.name === 'cmodexp' && r.dim === 512 && r.fold.length === 16), true)
  assert.equal(prove.receipts.rows.some((r) => r.name === 'xx' && r.dim === 512), true)
  const again = qpuProveOf()
  assert.equal(again.receipts.fold, prove.receipts.fold)
})

// THE KERNEL MUST NOT ALREADY KNOW THE ANSWER. theorem shor computes its own period and factors; the statement may
// carry only the instance (8, 91) and the small constants of the arithmetic, never 7, 13, or 4. And the file stays
// sorry-free, axiom-free, and decide-free, so every proof is a term the kernel reduced.
test('index.lean is sorry-free, axiom-free, decide-free, and theorem shor carries no answer', () => {
  assert.equal(/\bsorry\b/.test(leanSource), false)
  assert.equal(/^axiom\b/m.test(leanSource), false)
  assert.equal(leanSource.includes('by decide'), false)
  assert.equal(leanSource.includes('native_decide'), false)
  const line = leanSource.split('\n').find((l) => l.startsWith('theorem shor :'))
  assert.ok(line)
  const statement = line.slice(0, line.indexOf(':='))
  for (const fn of ['periodOf', 'half', 'gcdOf']) {
    assert.ok(statement.includes(fn), fn)
    assert.ok(leanSource.split('\n').some((l) => l.startsWith(`def ${fn} `)), `def ${fn}`)
  }
  const numerals = [...new Set(statement.match(/\d+/g) ?? [])].sort()
  assert.deepEqual(numerals, ['0', '1', '2', '8', '91'])
  const shor = qpuShorOf()
  assert.equal(shor.factors.p * shor.factors.q, shor.n)
  assert.equal(numerals.includes(String(shor.factors.p)), false)
  assert.equal(numerals.includes(String(shor.factors.q)), false)
  assert.equal(numerals.includes(String(shor.post.period)), false)
})
