import { test } from 'node:test'
import assert from 'node:assert/strict'
import { qpuMcpOf, qpuProveOf, qpuQuantumOf, qpuShorHolds, qpuShorOf } from './index.js'

test('Shor specifies N and a coprime base', () => {
  const shor = qpuShorOf()
  assert.equal(qpuShorHolds(shor), true)
  assert.equal(shor.n, 15)
  assert.equal(shor.a, 7)
  assert.equal(shor.coprime, true)
  assert.equal(shor.n % shor.a === 0, false)
})

test('Shor modular-exponentiation circuitry maps counting to a^x mod N', () => {
  const shor = qpuShorOf()
  assert.equal(shor.circuitry.kind, 'cmodexp')
  assert.deepEqual(shor.circuitry.native, ['h', 'cnot'])
  assert.equal(shor.circuitry.mul.length, 2)
  assert.equal(shor.circuitry.mul[0]?.a, 7)
  assert.equal(shor.circuitry.mul[1]?.a, 4)
  assert.equal(shor.circuitry.holds, true)
})

test('Shor period-finding is inverse QFT', () => {
  const shor = qpuShorOf()
  assert.equal(shor.qft.kind, 'iqft')
  assert.equal(shor.qft.qubits, 2)
  assert.equal(shor.qft.size, 4)
  assert.equal(shor.qft.holds, true)
  assert.equal(shor.post.kind, 'continued-fraction')
  assert.equal(shor.post.period, 4)
  assert.equal(shor.post.holds, true)
})

test('Shor repeats physical xx-noisy shots', () => {
  const shor = qpuShorOf()
  assert.equal(shor.device, 'superconducting')
  assert.equal(shor.measure.noise, 'xx')
  assert.equal(shor.measure.identity, true)
  assert.equal(shor.measure.shots, 8)
  assert.equal(shor.measure.outcomes.length, 8)
  assert.equal(shor.measure.support.length > 0, true)
  assert.equal(shor.measure.holds, true)
})

test('Shor post-processing factors multiply back to N', () => {
  const shor = qpuShorOf()
  assert.equal(shor.factors.p, 3)
  assert.equal(shor.factors.q, 5)
  assert.equal(shor.factors.product, 15)
  assert.equal(shor.factors.p * shor.factors.q, shor.n)
  assert.equal(shor.factors.holds, true)
  assert.equal(shor.payload, 'https://qpu.uuidna.com/storage/databases/payload')
})

test('purpose is fridge, Shor, extras, and next — not slogan flags', () => {
  const quantum = qpuQuantumOf()
  const prove = qpuProveOf()
  const purpose = quantum.purpose
  assert.equal(purpose.holds, true)
  assert.equal(purpose.kind, 'purpose')
  assert.equal(purpose.nature.platform, quantum.circuit.fridge.kind)
  assert.equal(purpose.nature.qubits, 3)
  assert.equal(purpose.nature.resistance, 0)
  assert.equal(purpose.nature.entangle, false)
  assert.equal(purpose.nature.ghz, true)
  assert.equal(purpose.cybersecurity.n, quantum.shor.n)
  assert.equal(purpose.cybersecurity.a, quantum.shor.a)
  assert.equal(purpose.cybersecurity.product, 15)
  assert.deepEqual(purpose.cybersecurity.factors, [3, 5])
  assert.equal(purpose.optimization.next, purpose.optimization.fused + purpose.optimization.fused)
  assert.equal(purpose.science.climb[3], 'qpu_prove')
  assert.deepEqual(purpose.science.extras, ['/storage', '/network', '/server'])
  assert.equal(purpose.sensing.network, '/network')
  assert.equal(purpose.sensing.server, '/server')
  assert.equal(purpose.sensing.hop, 'involution')
  assert.equal(prove.purpose.holds, true)
  assert.equal(prove.purpose.nature.platform, prove.circuit.hardware.device)
  assert.equal(prove.purpose.cybersecurity.product, prove.shor.n)
})

test('evidence is this-run provenance, calibration, QV-style heavy output, and cross-validation', () => {
  const quantum = qpuQuantumOf()
  const prove = qpuProveOf()
  const evidence = quantum.evidence
  assert.equal(evidence.holds, true)
  assert.equal(evidence.provenance.provider, 'qpu.uuidna.com')
  assert.equal(evidence.provenance.device, quantum.circuit.fridge.kind)
  assert.equal(evidence.provenance.shots, quantum.shor.measure.shots)
  assert.equal(evidence.provenance.outcomes.length, 8)
  assert.equal(evidence.provenance.counts.length, 2)
  assert.equal(evidence.provenance.weights.length, quantum.shor.qft.size)
  assert.deepEqual(evidence.provenance.compiler.native, ['h', 'cnot'])
  assert.equal(evidence.provenance.map.fridge, 3)
  assert.equal(evidence.noise.model, 'xx')
  assert.equal(evidence.noise.gate.identity, true)
  assert.equal(evidence.noise.t1.millikelvin, quantum.circuit.fridge.cryostat.mixing)
  assert.equal(evidence.noise.t2.millikelvin, quantum.circuit.fridge.cryostat.plate)
  assert.equal(evidence.noise.resistance, 0)
  assert.equal(evidence.noise.drift, true)
  assert.equal(evidence.volume.dim, 8)
  assert.equal(evidence.volume.threshold.num, 2)
  assert.equal(evidence.volume.threshold.den, 3)
  assert.equal(evidence.volume.uncertainty, 8)
  assert.equal(evidence.volume.randomized.includes('deutsch'), true)
  assert.equal(evidence.volume.randomized.includes('ghz'), false)
  assert.equal(evidence.cross.agreeIdeal, true)
  assert.equal(evidence.cross.noisy, 'xx')
  assert.equal(evidence.scaling.exact, true)
  assert.equal(evidence.scaling.beyond, false)
  assert.equal(evidence.scaling.advantage, false)
  assert.equal(evidence.verify.cors, '*')
  assert.equal(evidence.verify.origin, 'https://qpu.uuidna.com')
  assert.equal(evidence.verify.cern, 'opendata.cern.ch')
  assert.equal(evidence.verify.hardware, true)
  assert.equal(evidence.verify.algorithm, true)
  assert.equal(evidence.verify.crypt, true)
  assert.equal(evidence.fault.code, 'bitflip')
  assert.equal(evidence.fault.distance, 3)
  assert.equal(evidence.fault.codes, 1)
  assert.equal(evidence.fault.suppressed, true)
  assert.equal(evidence.fault.logical.off, 0)
  assert.equal(evidence.fault.logicalLtPhysical, true)
  assert.equal(prove.evidence.holds, true)
  assert.equal(prove.evidence.provenance.device, prove.circuit.hardware.device)
  assert.equal(prove.evidence.provenance.shots, prove.shor.shots)
})

test('Shor is on the sequence — quantum then lean then prove', () => {
  const shor = qpuShorOf()
  const quantum = qpuQuantumOf()
  const prove = qpuProveOf()
  const mcp = qpuMcpOf()
  assert.equal(quantum.shor.holds, true)
  assert.equal(quantum.shor.factors.p * quantum.shor.factors.q, quantum.shor.n)
  assert.equal(quantum.sequence.rungs[0]?.tool, 'qpu_quantum')
  assert.equal(quantum.sequence.rungs[0]?.path, '/')
  assert.equal(quantum.sequence.rungs[7]?.path, '/server')
  assert.equal(quantum.sequence.rungs[7]?.tool, 'qpu_prove')
  assert.equal(quantum.sequence.climb[3], 'qpu_prove')
  assert.equal(quantum.sequence.extras[0]?.path, '/storage')
  assert.equal(prove.shor.circuitry, 'cmodexp')
  assert.equal(prove.shor.qft, 'iqft')
  assert.equal(prove.shor.product, 15)
  assert.equal(mcp.prove.shor.n, 15)
  assert.equal(mcp.prove.shor.product, 15)
  assert.equal(shor.n, 15)
  assert.equal(shor.a, 7)
  assert.equal(shor.factors.p * shor.factors.q, shor.n)
})
