/** GENERATED by scripts/embed-lean.mjs from the gate receipts. Do not edit; run `npm run lean:embed`. */
export const sealedStandards = {
  "walls": 23,
  "lattice": 0,
  "refusals": 23,
  "refusalsTotal": 39,
  "dry": 0
} as const
