import { test } from './receipted.js'
import assert from 'node:assert/strict'
import { qpuAnalyticsHolds, qpuAnalyticsOf, qpuAnalyticsSentenceOf, qpuMachinesHolds, qpuMachinesOf, qpuMachinesSentenceOf, qpuPublicOf, qpuZeroPageHolds, qpuZeroPageOf } from './zeropage.js'

/** The byte page recomputes, and the summarised analytics hold every integer, including the amplitude count. */
test('zero page: analytics hold the register, the byte, and the counts past one byte', async (t) => {
  const page = await qpuZeroPageOf()
  const a = qpuAnalyticsOf()
  assert.equal(a.holds, true)
  assert.equal(qpuAnalyticsHolds(a), true)
  assert.equal(await qpuZeroPageHolds(page), true)
  const cell = (name: string) => page.cells.find((row) => row.name === name)
  for (const name of ['seed', 'coins', 'n', 'rays', 'clay', 'modulus', 'riemann', 'bsd', 'hodge', 'navierStokes', 'pVsNp', 'yangMills'] as const) {
    assert.equal(cell(name)?.value, a[name], name)
    assert.equal(cell(name)?.fits, true, name)
  }
  assert.equal(cell('hzLow')?.value, a.low)
  assert.equal(cell('hzHigh')?.value, a.high)
  assert.equal(page.ran.every((row) => row.agrees), true, page.ran.filter((row) => !row.agrees).map((row) => row.name).join(', '))
  assert.equal(page.leads.find((lead) => lead.name === 'amplitudes')?.fits, false)
  assert.equal(page.leads.find((lead) => lead.name === 'fused')?.fits, false)
  assert.equal(a.next, a.fused + a.fused)
  assert.notEqual(a.plane, a.fused)
  const face = qpuPublicOf(a)
  assert.equal(face.prize, false)
  assert.equal(face.sentence.includes('zeropoint-node 1.5.8'), true)
  assert.equal(face.sentence.includes('2026-09-07'), true)
  assert.equal(face.sentence.includes('2026-08-19'), true)
  assert.equal(face.sentence.includes('2025-07-08'), true)
  assert.equal(face.sentence.includes('0\\1\\2\\4\\8/7/5/3\\6\\9/0\\1'), true)
  assert.equal(face.sentence.includes('doi:10.5281/zenodo.21781602'), true)
  assert.equal(face.sentence.endsWith('A prize is a lead.'), true)
  assert.equal(face.lines.filter((line) => line.includes('A prize is a lead.')).length, 1)
  assert.equal(qpuAnalyticsSentenceOf(a).includes(String(a.amplitudes)), true)
  assert.equal(face.lines.some((line) => line.includes('CC-BY-NC-ND-4.0')), true)
  assert.equal(/is solved|prize was awarded|without holding/i.test(face.lines.join('\n')), false)
  t.diagnostic(face.sentence)
})

/** Word-size classes. Clay recomputes on every class whose store holds the integers. A one-register miss is a lead. */
test('machines: Pravets first, clay on every class that holds the integers', async (t) => {
  const m = qpuMachinesOf()
  const a = m.analytics
  assert.equal(m.holds, true)
  assert.equal(qpuMachinesHolds(m), true)
  assert.equal(m.prize, false)
  assert.equal(m.catalogEnds, false)
  assert.equal(m.walk.measured, false)
  assert.equal(a.seed, 1)
  assert.equal(a.coins, 2)
  assert.equal(a.n, 3)
  assert.equal(a.rays, 7)
  assert.equal(a.clay, 14)
  assert.equal(a.modulus, 91)
  assert.equal(a.hz, 432)
  assert.equal(a.amplitudes, 4294967296)
  assert.equal(a.fused, 120259084288)
  assert.equal(a.next, 240518168576)
  assert.equal(m.rows[0]?.name, 'Pravets 8M')
  assert.equal(m.rows[0]?.wordBits, 8)
  assert.equal(m.rows[0]?.amplitudesHeld, true)
  assert.equal(m.rows[0]?.fusedHeld, true)
  assert.equal(m.rows[0]?.oneRegisterFidelity, 0)
  assert.equal(m.rows[0]?.note, 'value 0; holds 1')
  assert.equal(m.rows[0]?.lead, true)
  assert.equal(m.rows[0]?.registerNext, '16-bit')
  assert.equal(m.rows[0]?.lawful, 1)
  const clay = m.rows[0]?.clay
  assert.equal(clay?.riemann, 1)
  assert.equal(clay?.hodge, 4)
  assert.equal(clay?.yangMills, 2)
  assert.equal(clay?.bsd, 2)
  assert.equal(clay?.bsdFaces, 2)
  assert.equal(clay?.navierStokes, 1)
  assert.equal(clay?.pVsNp, 0)
  assert.equal(clay?.holds, true)
  assert.equal(clay?.fidelity, 1)
  assert.equal(clay?.next, 'held')
  const row = (name: string) => m.rows.find((item) => item.name === name)
  assert.equal(row('Manchester Baby')?.fusedHeld, true)
  assert.equal(row('Manchester Baby')?.oneRegisterFidelity, 0)
  assert.equal(row('Manchester Baby')?.clay?.holds, true)
  assert.equal(row('ENIAC')?.digits, 10)
  assert.equal(row('ENIAC')?.amplitudesInOneRegister, true)
  assert.equal(row('ENIAC')?.fusedInOneRegister, false)
  assert.equal(row('ENIAC')?.clay?.holds, true)
  assert.equal(row('UNIVAC I')?.wordBits, 72)
  assert.equal(row('UNIVAC I')?.oneRegisterFidelity, 1)
  assert.equal(row('UNIVAC I')?.registerNext, 'held')
  assert.equal(row('PDP-8')?.wordBits, 12)
  assert.equal(row('PDP-8')?.oneRegisterFidelity, 0)
  assert.equal(row('PDP-8')?.registerNext, '16-bit')
  assert.equal(row('32-bit')?.amplitudesInOneRegister, false)
  assert.equal(row('32-bit')?.amplitudesRedirected, 1)
  assert.equal(row('32-bit')?.fusedHeld, true)
  assert.equal(row('32-bit')?.registerNext, '64-bit')
  assert.equal(row('64-bit')?.oneRegisterFidelity, 1)
  assert.equal(row('64-bit')?.fusedInOneRegister, true)
  assert.equal(row('64-bit')?.registerNext, 'held')
  assert.equal(row('modern')?.oneRegisterFidelity, 1)
  assert.equal(row('exact-amplitudes')?.advantage, false)
  assert.equal(row('exact-amplitudes')?.oneRegisterFidelity, 1)
  assert.equal(row('exact-amplitudes')?.clay?.next, 'held')
  for (const item of m.rows) {
    if (item.integersHeld) {
      assert.equal(item.clay?.riemann, clay?.riemann, item.name)
      assert.equal(item.clay?.hodge, clay?.hodge, item.name)
      assert.equal(item.clay?.yangMills, clay?.yangMills, item.name)
      assert.equal(item.clay?.bsd, clay?.bsd, item.name)
      assert.equal(item.clay?.bsdFaces, clay?.bsdFaces, item.name)
      assert.equal(item.clay?.navierStokes, clay?.navierStokes, item.name)
      assert.equal(item.clay?.pVsNp, clay?.pVsNp, item.name)
      assert.equal(item.clay?.holds, true, item.name)
      assert.equal(item.clay?.fidelity, 1, item.name)
    } else {
      assert.equal(item.clay, undefined, item.name)
      assert.equal(item.lead, true, item.name)
    }
  }
  const sentence = qpuMachinesSentenceOf(m)
  assert.equal(sentence.includes(String(a.amplitudes)), true)
  assert.equal(sentence.includes(String(a.fused)), true)
  assert.equal(sentence.includes('A prize is a lead.'), true)
  assert.equal(/is solved|prize was awarded|without holding/i.test(sentence), false)
  t.diagnostic(sentence)
  t.diagnostic(m.rows.map((item) => `${item.name} ${item.wordBits} amp ${item.amplitudesHeld} fused ${item.fusedHeld} fid ${item.oneRegisterFidelity} clay ${item.clay?.holds ?? 'lead'} ${item.clay?.next ?? item.registerNext}`).join('\n'))
})
