#!/usr/bin/env node
/**
 * Every public API, fused and used: the registry walked through the `api` family's addresses (dist/mcp/api-door.js).
 * An API is fused when its document was read and its operations derived; used when its first read operation needing no
 * parameter was called and answered (any status: the answer is the reading). Writes api-receipt.json.
 *
 *   node scripts/api-receipt.mjs            the whole registry
 *   node scripts/api-receipt.mjs --take 50  a slice
 */
import fs from 'node:fs'
import { apiWalkOf } from '../dist/mcp/api-door.js'
import { qpuContentUuidOf, qpuUuidReceiptOf } from '../dist/quantum/processing/unit/index.js'

// --registry: write src/mcp/registry.ts, the registry as of now reduced to what the door needs (name, preferred version's
// spec url, title, categories): generated, dated, a few hundred KB where the live list is 8 MB
if (process.argv.includes('--registry')) {
  const { apiRegistryOf } = await import('../dist/mcp/api-door.js')
  const r = await fetch('https://api.apis.guru/v2/list.json', { headers: { accept: 'application/json' } })
  const full = await r.json()
  const slim = Object.fromEntries(Object.entries(full).map(([api, e]) => {
    const v = e.versions?.[e.preferred ?? ''] ?? {}
    return [api, { preferred: e.preferred, versions: { [e.preferred ?? '']: { swaggerUrl: v.swaggerUrl, info: { title: v.info?.title, 'x-apisguru-categories': v.info?.['x-apisguru-categories'] ?? [] } } } }]
  }))
  const text = `/** GENERATED by scripts/api-receipt.mjs --registry from https://api.apis.guru/v2/list.json on ${new Date().toISOString().slice(0, 10)}: ${Object.keys(slim).length} APIs. Do not edit; rerun. */\nexport const REGISTRY_SNAPSHOT: Record<string, { preferred?: string; versions?: Record<string, { swaggerUrl?: string; info?: { title?: string; 'x-apisguru-categories'?: string[] } }> }> = ${JSON.stringify(slim)}\n`
  fs.writeFileSync('src/mcp/registry.ts', text)
  console.log(JSON.stringify({ registry: Object.keys(slim).length, bytes: text.length }))
  void apiRegistryOf
  process.exit(0)
}
const at = process.argv.indexOf('--take')
const take = at > 0 ? Number(process.argv[at + 1]) : Infinity
const t0 = Date.now()
const walk = await apiWalkOf(0, take, 16)
const why = walk.rows.filter((r) => !r.used).reduce((m, r) => ({ ...m, [r.why ?? `status ${r.status}`]: (m[r.why ?? `status ${r.status}`] ?? 0) + 1 }), {})
const statuses = walk.rows.filter((r) => r.used).reduce((m, r) => ({ ...m, [r.status]: (m[r.status] ?? 0) + 1 }), {})
const doc = {
  kind: 'api-receipt',
  when: new Date().toISOString().slice(0, 10),
  registry: walk.registry,
  listed: walk.listed,
  walked: walk.take,
  fused: walk.fused,
  used: walk.used,
  statuses,
  why,
  seconds: Math.round((Date.now() - t0) / 1000),
  holds: walk.fused === walk.take,
  rows: walk.rows.map((r) => ({ name: r.api, pass: r.used, value: `${r.fused ? `${r.operations} operations` : 'not fused'} · ${r.used ? `${r.status} ${r.url}` : r.why}`, receipt: '' })),
}
doc.uuid = qpuContentUuidOf(doc.rows)
doc.receipt = qpuUuidReceiptOf('api', doc.uuid, `${doc.used}/${doc.fused}/${doc.walked}`, 'scripts/api-receipt.mjs').uuid
fs.writeFileSync('api-receipt.json', JSON.stringify(doc, null, 1) + '\n')
console.log(JSON.stringify({ listed: doc.listed, walked: doc.walked, fused: doc.fused, used: doc.used, statuses, why, seconds: doc.seconds }))
