#!/usr/bin/env node
// embed-lean — copies src/quantum/processing/unit/index.lean into src/quantum/processing/unit/lean.ts as a string
// so the Worker (which has no filesystem) can serve the proof at its cited path. Run by hand after editing the
// Lean file; the build never runs it, so lean.test.ts can fail when the embed is stale (a gate that repairs cannot fail).
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { execSync } from 'node:child_process'

// the version embedded is the version the lock allows: v1.<minor>.<digit>, forward only
execSync('node scripts/version-lock.mjs --offline', { stdio: 'inherit' })

const root = process.cwd()
const leanPath = 'src/quantum/processing/unit/index.lean'
const source = readFileSync(join(root, leanPath), 'utf8')
const toolchain = readFileSync(join(root, 'lean-toolchain'), 'utf8').trim()

// PRECOMPUTE THE PROOF OFF THE HOT PATH. Every theorem's recompute (holds + typeset formula + its range) is evaluated
// here at build and embedded, so qpuLeanOf READS it instead of running ~290 leanRecomputeOf per cold isolate (~5.6s,
// which exceeded the Worker's CPU budget → 1102 on every door). Ground truth stays `lake build` + this build-time
// recompute; the runtime only reads. Needs dist (lean-eval) — run `npm run build` first; lean.test guards staleness.
const ev = await import(pathToFileURL(join(root, 'dist/quantum/processing/unit/lean-eval.js')).href)
const model = ev.leanModelOf(source)
const leanRecomputed = {}
for (const [name, theorem] of ev.leanTheoremBlocksOf(source)) {
  const r = ev.leanRecomputeOf(theorem, model)
  leanRecomputed[name] = r.over === undefined ? { holds: r.holds, formula: r.formula } : { holds: r.holds, over: r.over, formula: r.formula }
}

// COOL THE HOT CONSTANTS. Each heavy onceOf result (computer/quantum/circuit/lean) costs ~2.8s of V8 JIT on first call
// per cold isolate. Precompute them here and embed them so a tool handler serving default/{} args READS the embed and
// never calls the heavy function → it is never JIT-compiled → cold ≈ import + read. One mechanism (this embed), not a
// second system. --check fails on drift, and the gate recomputes these live at push, so "verify all it computes alone"
// still holds at build/gate while the runtime reads the cooled, drift-checked embed.
const idx = await import(pathToFileURL(join(root, 'dist/quantum/processing/unit/index.js')).href)
const prf = await import(pathToFileURL(join(root, 'dist/quantum/processing/unit/proof.js')).href)
const bigintSafe = (v) => JSON.parse(JSON.stringify(v, (_k, x) => (typeof x === 'bigint' ? x.toString() : x)))
// REGENERATE FROM LIVE, NOT FROM THE EMBED. qpuComputerOf/qpuQuantumOf/qpuCircuitOf now READ embeddedConstants at
// runtime (the cool), so calling them here would read this file's own prior output — a circular regeneration that can
// never correct a drift. The *LiveOf variants bypass the embed and compute from the lattice, so the embed is always a
// fresh function of the source. qpuLeanOf stays live (it reads no embed; its heavy deps are the cooled three).
const embeddedConstants = {
  computer: bigintSafe(idx.qpuComputerLiveOf()),
  quantum: bigintSafe(idx.qpuQuantumLiveOf()),
  circuit: bigintSafe(idx.qpuCircuitLiveOf()),
  lean: bigintSafe(prf.qpuLeanOf()),
}

const out = [
  `/** GENERATED by scripts/embed-lean.mjs from ${leanPath}. Do not edit; edit the Lean file and rerun \`npm run lean:embed\`. */`,
  `export const leanPath = ${JSON.stringify(leanPath)}`,
  `export const leanToolchain = ${JSON.stringify(toolchain)}`,
  `export const leanSource = ${JSON.stringify(source)}`,
  `export const leanRecomputed: Record<string, { holds: boolean; over?: string; formula: string }> = ${JSON.stringify(leanRecomputed)}`,
  '',
].join('\n')
writeFileSync(join(root, 'src/quantum/processing/unit/lean.ts'), out)
// the cooled heavy constants, read by the tool handlers for default/{} args (live-compute stays for custom args)
writeFileSync(
  join(root, 'src/quantum/processing/unit/embedded.ts'),
  `/** GENERATED by scripts/embed-lean.mjs: the heavy onceOf constants precomputed at build and embedded, bigint-safe, so a\n * cold Worker isolate serves default-arg results by READING this instead of JIT-compiling the heavy functions. Do not\n * edit; run \`npm run lean:embed\`. \`--check\` fails on drift and the gate recomputes these live at push. */\n` +
    `export const embeddedConstants: Record<'computer' | 'quantum' | 'circuit' | 'lean', unknown> = ${JSON.stringify(embeddedConstants)}\n`,
)
// The served version, read from package.json: the Worker has no filesystem, and tsc will not read a JSON outside rootDir.
const version = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version
writeFileSync(
  join(root, 'src/quantum/processing/unit/version.ts'),
  `/** GENERATED from package.json by scripts/version-lock.mjs (build) and scripts/embed-lean.mjs. Do not edit; bump package.json. */\nexport const packageVersion: string = ${JSON.stringify(version)}\n`,
)
/**
 * THE STANDARDS THIS TREE HOLDS ITSELF TO, SEALED SO THE UNIT CAN SERVE THEM.
 *
 * Eight gates write receipts — walls, lattice, refusals, the dry-clean floor inside the test receipt — and
 * nothing gathered them. Answering "is this tree holding its own standards" meant running six commands by
 * hand and reading six outputs, which is the manual handling those gates exist to remove.
 *
 * A Worker has no filesystem, so the unit cannot read its own receipts at runtime. They are baked here
 * instead, the way the version already is, and served from the unit — so one MCP call answers it and a test
 * can prove the served numbers are the files. A stale bake then fails rather than reassures.
 */
const receiptOf = (file, pick) => {
  try {
    return pick(JSON.parse(readFileSync(join(root, file), 'utf8')))
  } catch {
    return undefined
  }
}
const standards = {
  walls: receiptOf('walls-receipt.json', (r) => r.walls),
  lattice: receiptOf('lattice-receipt.json', (r) => r.literals),
  refusals: receiptOf('refusals-receipt.json', (r) => r.notCross),
  refusalsTotal: receiptOf('refusals-receipt.json', (r) => r.refusals),
  dry: receiptOf('test-receipt.json', (r) => r.dry),
}
writeFileSync(
  join(root, 'src/quantum/processing/unit/standards.ts'),
  `/** GENERATED by scripts/embed-lean.mjs from the gate receipts. Do not edit; run \`npm run lean:embed\`. */\n` +
    `export const sealedStandards = ${JSON.stringify(standards, null, 2)} as const\n`,
)
console.log(`embed-lean: ${source.length} chars, ${toolchain}, v${version}, standards ${JSON.stringify(standards)}`)
