#!/usr/bin/env node
// embed-lean — copies src/quantum/processing/unit/index.lean into src/quantum/processing/unit/lean.ts as a string
// so the Worker (which has no filesystem) can serve the proof at its cited path. Run by hand after editing the
// Lean file; the build never runs it, so lean.test.ts can fail when the embed is stale (a gate that repairs cannot fail).
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()
const leanPath = 'src/quantum/processing/unit/index.lean'
const source = readFileSync(join(root, leanPath), 'utf8')
const toolchain = readFileSync(join(root, 'lean-toolchain'), 'utf8').trim()
const out = [
  `/** GENERATED by scripts/embed-lean.mjs from ${leanPath}. Do not edit; edit the Lean file and rerun \`npm run lean:embed\`. */`,
  `export const leanPath = ${JSON.stringify(leanPath)}`,
  `export const leanToolchain = ${JSON.stringify(toolchain)}`,
  `export const leanSource = ${JSON.stringify(source)}`,
  '',
].join('\n')
writeFileSync(join(root, 'src/quantum/processing/unit/lean.ts'), out)
console.log(`embed-lean: ${source.length} chars, ${toolchain}`)
