/** GENERATED by scripts/lattice.mjs from the lattice. Do not edit; run `npm run lattice:fix`. */
export const faces = 14
export const rays = 7
export const coins = 2
export const vertices = 8
export const hexbit = 4
export const bits = 32
export const mintOf = (k) => coins ** k
export const tenOf = (k) => 10 ** k
