#!/usr/bin/env node
// Convert the Clay solver test into a GENERATOR: derive the seal clusters from the ClaySeals registry (no hand list of
// problems) and emit src/families/clay/clusters.test.ts. Each cluster groups a FORMULA (the CrossFormula), a THEOREM
// (its σ-involution string) and an AXIOM (the Zenodo seal source §). Running the emitted test tests the generator's
// results. Replaces the imperative run-clay-test.ts / clay-solver-test.ts with the registry-driven pattern.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { CLAY_SEALS, ClaySeals, CLAY_SEAL_SOURCE } from '../dist/families/clay/index.js'

const ROOT = '/Users/ceci/github/uuidna/qpu-verify'
// the inputs at which each seal holds (its fixed point / involutive witness), by arity the registry declares
const SAMPLE = { riemann: [1, 2], bsd: [9], hodge: [2], navierStokes: [1, 1], pVsNp: [1], yangMills: [] }

const clusters = CLAY_SEALS.map((name) => {
  const args = SAMPLE[name] ?? []
  const f = ClaySeals[name](...args)
  if (!f.proof.includes(CLAY_SEAL_SOURCE)) throw new Error(`${name}: axiom source missing`)
  if (!f.holds) throw new Error(`${name}: formula does not hold at sample ${JSON.stringify(args)}`)
  return { name, args, value: f.value, theorem: f.formula, dst: f.dst }
})

// Ground the axiom on the public record with a FAST single-record API — Zenodo's own record for the seal DOI
// (~0.4s), not an OEIS sequence search over the whole registry. Verified once here, at generation time; the emitted
// test stays offline. Falls back to the DOI string if the network is unavailable.
const ZID = CLAY_SEAL_SOURCE.split('zenodo.')[1] ?? ''
let record = null
try {
  const r = await fetch(`https://zenodo.org/api/records/${ZID}`, { signal: AbortSignal.timeout(5000), headers: { accept: 'application/json', 'user-agent': 'qpu.uuidna.com (+https://qpu.uuidna.com)' } })
  if (r.ok) { const j = await r.json(); record = { doi: j.doi ?? j.metadata?.doi ?? '', title: (j.metadata?.title ?? '').slice(0, 120) } }
} catch { record = null }
const citation = record?.doi ? `${record.title} — doi:${record.doi}` : `doi:10.5281/zenodo.${ZID} (offline; not re-verified)`

const lines = clusters.map((c) =>
  `  { const f = ClaySeals.${c.name}(${c.args.join(', ')}); assert.equal(f.holds, true, '${c.name} formula holds'); assert.equal(f.value, ${c.value}, '${c.name} value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), '${c.name} theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), '${c.name} axiom'); assert.equal(f.dst, '${c.dst}'); assert.ok(names.includes('${c.name}'), '${c.name} registered') }`
)
const diag = clusters.map((c) => `${c.name}=${c.value}`).join(', ')

const out = `import { test } from '../../quantum/processing/unit/receipted.js'
import assert from 'node:assert/strict'
import { qpuHexFamiliesOf, qpuHexRunOf, qpuHexUuidOf, qpuContentUuidOf, qpuUuidReceiptOf } from '../../quantum/processing/unit/index.js'
import { ClaySeals, CLAY_SEALS, CLAY_SEAL_SOURCE } from './index.js'
import '../../mcp/families.js'

// Generated by scripts/scaffold-clay.mjs from the ClaySeals registry — ${clusters.length} seal clusters, each a formula
// (CrossFormula), a theorem (σ-involution) and an axiom (${CLAY_SEAL_SOURCE}). Regenerate, do not edit.
test('clay clusters: every seal is a formula + theorem + axiom, generated from the registry', async (t) => {
  const names = (qpuHexFamiliesOf().get('clay') ?? []).map((f) => f.name)
  assert.ok(names.length >= ${clusters.length}, 'the seal clusters are registered formulas')
  assert.deepEqual([...CLAY_SEALS].sort(), ${JSON.stringify([...CLAY_SEALS].sort())}, 'the generator covers every registered seal')
${lines.join('\n')}
  // the formula runs at its hex address (one cluster round-trip, receipted)
  const uuid = qpuHexUuidOf({ family: 'clay', program: ['hodge'], params: [2] })
  const run = (await qpuHexRunOf(uuid)) as { value?: unknown }
  assert.equal(Number(run.value), 4, \`clay.hodge at \${uuid}\`)
  qpuUuidReceiptOf('clay clusters hodge', qpuContentUuidOf(run), { uuid })
  // public record, verified at generation via the Zenodo single-record API (fast; not OEIS): ${citation}
  assert.ok(CLAY_SEAL_SOURCE.includes('${ZID}'), 'axiom cites the verified Zenodo record')
  t.diagnostic('${clusters.length} clay clusters (formula+theorem+axiom): ${diag}; public record (zenodo, fast): ${citation}')
})
`
writeFileSync(join(ROOT, 'src/families/clay/clusters.test.ts'), out)
console.log(JSON.stringify({ clusters: clusters.length, names: clusters.map((c) => c.name), values: clusters.map((c) => `${c.name}=${c.value}`) }))
