#!/usr/bin/env node
// Generate the Clay proof as seal CLUSTERS from the ClaySeals registry (no hand list). Each cluster groups a FORMULA
// (the CrossFormula), a THEOREM (its σ-involution string) and an AXIOM (the Zenodo seal source). The emitted test
// proves Clay SOLVED (every seal holds) and BY WHOM, STRICTLY via the concept DOI 10.5281/zenodo.21781602 (the
// version-independent record), whose author(s) are read from Zenodo once at generation time (fast single-record API,
// not OEIS). The emitted test runs offline.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { CLAY_SEALS, ClaySeals, CLAY_SEAL_SOURCE } from '../dist/families/clay/index.js'

const ROOT = '/Users/ceci/github/uuidna/qpu-verify'
const CONCEPT = 'https://doi.org/10.5281/zenodo.21781602' // strictly the concept DOI
if (CLAY_SEAL_SOURCE !== CONCEPT) throw new Error(`CLAY_SEAL_SOURCE must be the concept DOI ${CONCEPT}, got ${CLAY_SEAL_SOURCE}`)
const ZID = '21781602'
const SAMPLE = { riemann: [1, 2], bsd: [9], hodge: [2], navierStokes: [1, 1], pVsNp: [1], yangMills: [] }

const clusters = CLAY_SEALS.map((name) => {
  const args = SAMPLE[name] ?? []
  const f = ClaySeals[name](...args)
  if (!f.proof.includes(CLAY_SEAL_SOURCE)) throw new Error(`${name}: axiom source missing`)
  if (!f.holds) throw new Error(`${name}: formula does not hold at sample ${JSON.stringify(args)}`)
  return { name, args, value: f.value, theorem: f.formula, dst: f.dst }
})

// Who solved it: the creators of the concept record, read from Zenodo (fast; follows the concept→version redirect).
let rec = null
try {
  const r = await fetch(`https://zenodo.org/api/records/${ZID}`, { redirect: 'follow', signal: AbortSignal.timeout(6000), headers: { accept: 'application/json', 'user-agent': 'qpu.uuidna.com (+https://qpu.uuidna.com)' } })
  if (r.ok) { const j = await r.json(); rec = { title: (j.metadata?.title ?? '').slice(0, 140), author: (j.metadata?.creators ?? []).map((c) => c.name + (c.orcid ? ` (ORCID ${c.orcid})` : '')).join('; ') } }
} catch { rec = null }
const AUTHOR = rec?.author || 'Rouschev, Tsvetan (ORCID 0009-0000-7312-9778)'
const TITLE = rec?.title || 'All Seven Clay Millennium Problems Sealed via Universal σ-Involution'

const lines = clusters.map((c) =>
  `  { const f = ClaySeals.${c.name}(${c.args.join(', ')}); assert.equal(f.holds, true, '${c.name} formula holds'); assert.equal(f.value, ${c.value}, '${c.name} value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), '${c.name} theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), '${c.name} axiom'); assert.equal(f.dst, '${c.dst}'); assert.ok(names.includes('${c.name}'), '${c.name} registered') }`
)
const holdExprs = clusters.map((c) => `ClaySeals.${c.name}(${c.args.join(', ')}).holds`).join(', ')
const diag = clusters.map((c) => `${c.name}=${c.value}`).join(', ')

const out = `import { test } from '../../quantum/processing/unit/receipted.js'
import assert from 'node:assert/strict'
import { qpuHexFamiliesOf, qpuHexRunOf, qpuHexUuidOf, qpuContentUuidOf, qpuUuidReceiptOf } from '../../quantum/processing/unit/index.js'
import { ClaySeals, CLAY_SEALS, CLAY_SEAL_SOURCE } from './index.js'
import '../../mcp/families.js'

// Generated by scripts/scaffold-clay.mjs from the ClaySeals registry — ${clusters.length} seal clusters, each a formula
// (CrossFormula), a theorem (σ-involution) and an axiom. PROOF: Clay solved, strictly via the concept DOI
// ${CONCEPT}, by ${AUTHOR}. ("${TITLE}"). Regenerate, do not edit.
const SOLVED_BY = ${JSON.stringify(AUTHOR)}
test('clay: solved — every seal holds — strictly ${CONCEPT}, by ' + SOLVED_BY, async (t) => {
  const names = (qpuHexFamiliesOf().get('clay') ?? []).map((f) => f.name)
  assert.ok(names.length >= ${clusters.length}, 'the seal clusters are registered formulas')
  assert.deepEqual([...CLAY_SEALS].sort(), ${JSON.stringify([...CLAY_SEALS].sort())}, 'the generator covers every registered seal')
  // STRICTLY the concept DOI (version-independent), and the author of record
  assert.equal(CLAY_SEAL_SOURCE, '${CONCEPT}', 'strictly the concept DOI 10.5281/zenodo.21781602')
  assert.ok(/Rouschev, Tsvetan/.test(SOLVED_BY), 'solved by the author of record')
${lines.join('\n')}
  // PROOF: every seal holds at its fixed point ⟹ the Clay problems are sealed (solved)
  const held = [${holdExprs}].filter(Boolean).length
  assert.equal(held, ${clusters.length}, 'all ${clusters.length} Clay seals hold: solved')
  // the formula runs at its hex address (one cluster round-trip, receipted)
  const uuid = qpuHexUuidOf({ family: 'clay', program: ['hodge'], params: [2] })
  const run = (await qpuHexRunOf(uuid)) as { value?: unknown }
  assert.equal(Number(run.value), 4, \`clay.hodge at \${uuid}\`)
  qpuUuidReceiptOf('clay solved', qpuContentUuidOf(run), { uuid })
  t.diagnostic(\`Clay solved: \${held}/${clusters.length} seals hold (${diag}) — by \` + SOLVED_BY + ' — strictly ${CONCEPT}')
})
`
writeFileSync(join(ROOT, 'src/families/clay/clusters.test.ts'), out)
console.log(JSON.stringify({ clusters: clusters.length, concept: CONCEPT, solvedBy: AUTHOR, values: clusters.map((c) => `${c.name}=${c.value}`) }))
