/**
 * QPU IS THE EXAMPLE OF BEST STANDARDS, BY ARCHITECTURE. The families make best practice structural, not hand-tuned:
 * every page's SEO, the site's accessibility and structured data, and the generated-from-code discipline are produced by
 * the generator and held by the gate — at the scale of a thousand-plus families. This reads the source and holds the
 * standards, so a regression fails here. Discovered by the scripts/*.test.mjs glob, run by the one gate.
 */
import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync, readdirSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'

const ROOT = join(dirname(new URL(import.meta.url).pathname), '..')
const read = (f) => (existsSync(join(ROOT, f)) ? readFileSync(join(ROOT, f), 'utf8') : '')

test('best SEO by architecture: the metadata generator produces the full best-practice set', () => {
  const m = read('src/utilities/metadataOf.ts')
  for (const field of ['title', 'description', 'canonical', 'openGraph', 'twitter', 'robots']) assert.match(m, new RegExp(field), `metadataOf produces ${field}`)
  const slug = read('src/app/(frontend)/(pages)/[...slug]/page.tsx')
  assert.match(slug, /canonical/, 'the catch-all sets a canonical for programs and UUIDs')
  assert.match(slug, /askOf|intelligent/i, 'any meaningful path resolves (200, not 404) so path changes do not break SEO')
})

test('best standards: accessibility, structured data, absolute URLs', () => {
  const layout = read('src/app/(frontend)/layout.tsx')
  assert.match(layout, /lang=/, 'the site declares a language (a11y)')
  assert.match(layout, /metadataBase/, 'absolute URLs via metadataBase')
  assert.match(layout, /ld\+json|application\/ld/, 'structured data (JSON-LD)')
})

test('best standards are generated from code, not hand-written', () => {
  assert.match(read('src/mcp/families.ts'), /regenerate, do not edit|Generated by/, 'the registry is generated')
  // no hand-written docs masquerading as pages (SEO/quality then reflect the code)
  const skill = read('.claude/skills/qpu-families/SKILL.md')
  assert.match(skill, /generated from the registry|generate-skills/, 'the skill is generated from the registry')
})

test('best standards at scale: the gate suite holds the whole surface, and the registry is large', async () => {
  const gates = readdirSync(join(ROOT, 'scripts')).filter((f) => f.endsWith('.test.mjs'))
  assert.ok(gates.length >= 10, `${gates.length} gates run on every push`)
  await import('../dist/mcp/families.js')
  const { qpuHexFamiliesOf } = await import('../dist/quantum/processing/unit/index.js')
  const n = [...qpuHexFamiliesOf().keys()].filter((f) => /^[a-z]+$/.test(f)).length
  assert.ok(n >= 100, `best standards hold across ${n} families (at scale)`)
})
