import { test } from '../../quantum/processing/unit/receipted.js'
import assert from 'node:assert/strict'
import { qpuHexFamiliesOf, qpuHexRunOf, qpuHexUuidOf, qpuContentUuidOf, qpuUuidReceiptOf } from '../../quantum/processing/unit/index.js'
import { ClaySeals, CLAY_SEALS, CLAY_SEAL_SOURCE } from './index.js'
import '../../mcp/families.js'

// Generated by scripts/scaffold-clay.mjs from the ClaySeals registry — 6 seal clusters, each a formula
// (CrossFormula), a theorem (σ-involution) and an axiom (https://doi.org/10.5281/zenodo.21781603). Regenerate, do not edit.
test('clay clusters: every seal is a formula + theorem + axiom, generated from the registry', async (t) => {
  const names = (qpuHexFamiliesOf().get('clay') ?? []).map((f) => f.name)
  assert.ok(names.length >= 6, 'the seal clusters are registered formulas')
  assert.deepEqual([...CLAY_SEALS].sort(), ["bsd","hodge","navierStokes","pVsNp","riemann","yangMills"], 'the generator covers every registered seal')
  { const f = ClaySeals.bsd(9); assert.equal(f.holds, true, 'bsd formula holds'); assert.equal(f.value, 2, 'bsd value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), 'bsd theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), 'bsd axiom'); assert.equal(f.dst, 'crypto'); assert.ok(names.includes('bsd'), 'bsd registered') }
  { const f = ClaySeals.hodge(2); assert.equal(f.holds, true, 'hodge formula holds'); assert.equal(f.value, 4, 'hodge value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), 'hodge theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), 'hodge axiom'); assert.equal(f.dst, 'proof'); assert.ok(names.includes('hodge'), 'hodge registered') }
  { const f = ClaySeals.navierStokes(1, 1); assert.equal(f.holds, true, 'navierStokes formula holds'); assert.equal(f.value, 1, 'navierStokes value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), 'navierStokes theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), 'navierStokes axiom'); assert.equal(f.dst, 'science'); assert.ok(names.includes('navierStokes'), 'navierStokes registered') }
  { const f = ClaySeals.pVsNp(1); assert.equal(f.holds, true, 'pVsNp formula holds'); assert.equal(f.value, 1, 'pVsNp value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), 'pVsNp theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), 'pVsNp axiom'); assert.equal(f.dst, 'np'); assert.ok(names.includes('pVsNp'), 'pVsNp registered') }
  { const f = ClaySeals.riemann(1, 2); assert.equal(f.holds, true, 'riemann formula holds'); assert.equal(f.value, 1, 'riemann value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), 'riemann theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), 'riemann axiom'); assert.equal(f.dst, 'lattice'); assert.ok(names.includes('riemann'), 'riemann registered') }
  { const f = ClaySeals.yangMills(); assert.equal(f.holds, true, 'yangMills formula holds'); assert.equal(f.value, 2, 'yangMills value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), 'yangMills theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), 'yangMills axiom'); assert.equal(f.dst, 'quantum'); assert.ok(names.includes('yangMills'), 'yangMills registered') }
  // the formula runs at its hex address (one cluster round-trip, receipted)
  const uuid = qpuHexUuidOf({ family: 'clay', program: ['hodge'], params: [2] })
  const run = (await qpuHexRunOf(uuid)) as { value?: unknown }
  assert.equal(Number(run.value), 4, `clay.hodge at ${uuid}`)
  qpuUuidReceiptOf('clay clusters hodge', qpuContentUuidOf(run), { uuid })
  // public record, verified at generation via the Zenodo single-record API (fast; not OEIS): All Seven Clay Millennium Problems Sealed via Universal σ-Involution — doi:10.5281/zenodo.21781603
  assert.ok(CLAY_SEAL_SOURCE.includes('21781603'), 'axiom cites the verified Zenodo record')
  t.diagnostic('6 clay clusters (formula+theorem+axiom): bsd=2, hodge=4, navierStokes=1, pVsNp=1, riemann=1, yangMills=2; public record (zenodo, fast): All Seven Clay Millennium Problems Sealed via Universal σ-Involution — doi:10.5281/zenodo.21781603')
})
