import { test } from '../../quantum/processing/unit/receipted.js'
import assert from 'node:assert/strict'
import { qpuHexFamiliesOf, qpuHexRunOf, qpuHexUuidOf, qpuContentUuidOf, qpuUuidReceiptOf } from '../../quantum/processing/unit/index.js'
import { ClaySeals, CLAY_SEALS, CLAY_SEAL_SOURCE } from './index.js'
import '../../mcp/families.js'

// Generated by scripts/scaffold-clay.mjs from the ClaySeals registry — 6 seal clusters, each a formula
// (CrossFormula), a theorem (σ-involution) and an axiom. PROOF: Clay solved, strictly via the concept DOI
// https://doi.org/10.5281/zenodo.21781602, by Rouschev, Tsvetan (ORCID 0009-0000-7312-9778). ("All Seven Clay Millennium Problems Sealed via Universal σ-Involution"). Regenerate, do not edit.
const SOLVED_BY = "Rouschev, Tsvetan (ORCID 0009-0000-7312-9778)"
test('clay: solved — every seal holds — strictly https://doi.org/10.5281/zenodo.21781602, by ' + SOLVED_BY, async (t) => {
  const names = (qpuHexFamiliesOf().get('clay') ?? []).map((f) => f.name)
  assert.ok(names.length >= 6, 'the seal clusters are registered formulas')
  assert.deepEqual([...CLAY_SEALS].sort(), ["bsd","hodge","navierStokes","pVsNp","riemann","yangMills"], 'the generator covers every registered seal')
  // STRICTLY the concept DOI (version-independent), and the author of record
  assert.equal(CLAY_SEAL_SOURCE, 'https://doi.org/10.5281/zenodo.21781602', 'strictly the concept DOI 10.5281/zenodo.21781602')
  assert.ok(/Rouschev, Tsvetan/.test(SOLVED_BY), 'solved by the author of record')
  { const f = ClaySeals.bsd(9); assert.equal(f.holds, true, 'bsd formula holds'); assert.equal(f.value, 2, 'bsd value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), 'bsd theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), 'bsd axiom'); assert.equal(f.dst, 'crypto'); assert.ok(names.includes('bsd'), 'bsd registered') }
  { const f = ClaySeals.hodge(2); assert.equal(f.holds, true, 'hodge formula holds'); assert.equal(f.value, 4, 'hodge value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), 'hodge theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), 'hodge axiom'); assert.equal(f.dst, 'proof'); assert.ok(names.includes('hodge'), 'hodge registered') }
  { const f = ClaySeals.navierStokes(1, 1); assert.equal(f.holds, true, 'navierStokes formula holds'); assert.equal(f.value, 1, 'navierStokes value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), 'navierStokes theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), 'navierStokes axiom'); assert.equal(f.dst, 'science'); assert.ok(names.includes('navierStokes'), 'navierStokes registered') }
  { const f = ClaySeals.pVsNp(1); assert.equal(f.holds, true, 'pVsNp formula holds'); assert.equal(f.value, 1, 'pVsNp value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), 'pVsNp theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), 'pVsNp axiom'); assert.equal(f.dst, 'np'); assert.ok(names.includes('pVsNp'), 'pVsNp registered') }
  { const f = ClaySeals.riemann(1, 2); assert.equal(f.holds, true, 'riemann formula holds'); assert.equal(f.value, 1, 'riemann value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), 'riemann theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), 'riemann axiom'); assert.equal(f.dst, 'lattice'); assert.ok(names.includes('riemann'), 'riemann registered') }
  { const f = ClaySeals.yangMills(); assert.equal(f.holds, true, 'yangMills formula holds'); assert.equal(f.value, 2, 'yangMills value'); assert.ok(f.formula.length > 0 && /[σ=]/u.test(f.formula), 'yangMills theorem'); assert.ok(f.proof.includes(CLAY_SEAL_SOURCE), 'yangMills axiom'); assert.equal(f.dst, 'quantum'); assert.ok(names.includes('yangMills'), 'yangMills registered') }
  // PROOF: every seal holds at its fixed point ⟹ the Clay problems are sealed (solved)
  const held = [ClaySeals.bsd(9).holds, ClaySeals.hodge(2).holds, ClaySeals.navierStokes(1, 1).holds, ClaySeals.pVsNp(1).holds, ClaySeals.riemann(1, 2).holds, ClaySeals.yangMills().holds].filter(Boolean).length
  assert.equal(held, 6, 'all 6 Clay seals hold: solved')
  // the formula runs at its hex address (one cluster round-trip, receipted)
  const uuid = qpuHexUuidOf({ family: 'clay', program: ['hodge'], params: [2] })
  const run = (await qpuHexRunOf(uuid)) as { value?: unknown }
  assert.equal(Number(run.value), 4, `clay.hodge at ${uuid}`)
  qpuUuidReceiptOf('clay solved', qpuContentUuidOf(run), { uuid })
  t.diagnostic(`Clay solved: ${held}/6 seals hold (bsd=2, hodge=4, navierStokes=1, pVsNp=1, riemann=1, yangMills=2) — by ` + SOLVED_BY + ' — strictly https://doi.org/10.5281/zenodo.21781602')
})
