// discovery — the well-known document. Shared by the worker and the MCP catalog (one source).
import { DONATE_URL, qpuLicenceHostOf, donateUrl } from './hologram.js'

export const qpuDiscoveryOf = (origin: string) => ({
  worker: 'uuidna-qpu',
  host: qpuLicenceHostOf(),
  origin,
  donate: donateUrl(origin),
  wallet: DONATE_URL,
  mcp: `${origin}/mcp`,
  readings: ['seat', 'width', 'hologram', 'chip', 'merkaba', 'experience', 'live', 'metrics', 'speed', 'fractal', 'scale', 'og', 'nav', 'sidebar', 'search', 'superpositions', 'gateways', 'bindings', 'environment', 'standing', 'events', 'boot', 'pqc', 'quantum', 'licence', 'messenger', 'chat', 'train', 'config', 'pwa'] as const,
  endpoints: {
    '/': 'three readings, one machine, environment auto-recognized and fused',
    '/seat': 'LANES QPU — empty chip; environment still fused',
    '/width': 'BindingPoint pentagram — CPU GPU RAM CACHE STORAGE',
    '/hologram': 'octet planes; HTML is fourteen labeled VE faces',
    '/chip': 'novelty chip — two 7-ray rosettes fused at 0, CPU/GPU self-balance',
    '/merkaba': 'same reading as /chip',
    '/experience': 'inner and outer rotors — one involution',
    '/live': 'occupancy now — k walks fourteen VE faces',
    '/metrics': 'formula vs peer, every row must match',
    '/speed': 'constructor µs vs 2^n climbs for n that finish',
    '/fractal': 'fused pentagram · hologram · fourteen faces · all serverless',
    '/scale': 'peers + native transports + serverless lanes',
    '/og': 'hero Open Graph constructor — 1200×630',
    '/og.svg': 'hero Open Graph card — same pentagram as the homepage',
    '/sse': 'server-sent events of scale and live occupancy',
    '/ws': 'WebSocket — MCP JSON-RPC or {op}',
    '/peers': 'sandbox HTTP origins — licence host plus named fuse domains',
    '/nav': 'nav computed upon request',
    '/sidebar': 'sidebar computed upon request (?path=)',
    '/search': 'deep site analysis of every licensed host; constructors only (?q=&site=&kind=)',
    '/superpositions': 'fourteen VE faces with referer, door, angles',
    '/gateways': 'fourteen VE-face neighbours are capacity gateways — every handle bit is a usable mask',
    '/bindings': 'src/bindings/* — every provider fused; drivers auto-recognize env',
    '/solids': 'platonic solids plus shared pentagram — all APIs merge on CPU GPU RAM CACHE STORAGE',
    '/providers': 'cloudflare google aws azure ibm oracle hardware arch',
    '/environment': 'sandbox: HTTP of named domains, experiments unlimited, empty chip',
    '/pqc': 'all VE faces; target empty; when never',
    '/quantum': 'live working QPU — pure, agnostic, every possibility',
    '/licence': 'offline occupancy certificate — named host, no wildcards, when never',
    '/messenger': 'sequence is the uuid messenger — RFC 9562 clock_seq, fourteen standards, fourteen faces',
    '/chat': 'realtime occupancy — every input, uuid messenger, inference bills a user account via /bindings',
    '/room': 'same reading as /chat',
    '/train': 'occupancy corpus — fourteen lessons fused with uuidna keyless APIs, BindingPoint hardware, constructor APIs, asset skip, relations, and leads; named uuidna.com HTTPS only; never a crawl',
    '/config': 'shared configs — vitepress hologram and payload cms fuse on one node/typescript/wrangler table; vitepress defineLoader occupies payload CRUD, not graphql; replica host and title stay local',
    '/pwa': 'full-featured PWA of the QPU itself — proof of concept and proof of work; one hologram plugin; fractal named HTTPS; when never',
    '/standing': 'uuidna Lean keys this worker cites',
    '/events': 'fourteen UI event kinds occupying VE faces',
    '/boot': 'boot matrix — eight Alpine ISAs times trinity parts',
    '/sitemap.xml': 'constructor sitemap',
    '/robots.txt': 'Allow / and Sitemap',
    '/mcp': 'JSON-RPC MCP (GET discovery, POST tools/call)',
    '/.well-known/qpu.json': 'this document',
    '/.well-known/mcp.json': 'MCP discovery',
  },
})
