// Generated by scripts/payload-cloudflare.mjs from the committed *-receipt.json files — regenerate, do not edit
import api from '../../api-receipt.json'
import cross from '../../cross-receipt.json'
import debts from '../../debts-receipt.json'
import discovery from '../../discovery-receipt.json'
import flaws from '../../flaws-receipt.json'
import formulas from '../../formulas-receipt.json'
import funding from '../../funding-receipt.json'
import fuse from '../../fuse-receipt.json'
import gate from '../../gate-receipt.json'
import heat from '../../heat-receipt.json'
import lattice from '../../lattice-receipt.json'
import lean from '../../lean-receipt.json'
import next from '../../next-receipt.json'
import payloadCf from '../../payload-cf-receipt.json'
import percall from '../../percall-receipt.json'
import refusals from '../../refusals-receipt.json'
import test from '../../test-receipt.json'
import uses from '../../uses-receipt.json'
import walls from '../../walls-receipt.json'

export type Receipt = { file: string; name: string; doc: Record<string, unknown> }
/** The committed receipts: `file` as committed (heat-receipt.json), `name` the page it makes (heat-receipt). */
export const receipts: Receipt[] = [{ file: 'api-receipt.json', name: 'api-receipt', doc: api as Record<string, unknown> }, { file: 'cross-receipt.json', name: 'cross-receipt', doc: cross as Record<string, unknown> }, { file: 'debts-receipt.json', name: 'debts-receipt', doc: debts as Record<string, unknown> }, { file: 'discovery-receipt.json', name: 'discovery-receipt', doc: discovery as Record<string, unknown> }, { file: 'flaws-receipt.json', name: 'flaws-receipt', doc: flaws as Record<string, unknown> }, { file: 'formulas-receipt.json', name: 'formulas-receipt', doc: formulas as Record<string, unknown> }, { file: 'funding-receipt.json', name: 'funding-receipt', doc: funding as Record<string, unknown> }, { file: 'fuse-receipt.json', name: 'fuse-receipt', doc: fuse as Record<string, unknown> }, { file: 'gate-receipt.json', name: 'gate-receipt', doc: gate as Record<string, unknown> }, { file: 'heat-receipt.json', name: 'heat-receipt', doc: heat as Record<string, unknown> }, { file: 'lattice-receipt.json', name: 'lattice-receipt', doc: lattice as Record<string, unknown> }, { file: 'lean-receipt.json', name: 'lean-receipt', doc: lean as Record<string, unknown> }, { file: 'next-receipt.json', name: 'next-receipt', doc: next as Record<string, unknown> }, { file: 'payload-cf-receipt.json', name: 'payload-cf-receipt', doc: payloadCf as Record<string, unknown> }, { file: 'percall-receipt.json', name: 'percall-receipt', doc: percall as Record<string, unknown> }, { file: 'refusals-receipt.json', name: 'refusals-receipt', doc: refusals as Record<string, unknown> }, { file: 'test-receipt.json', name: 'test-receipt', doc: test as Record<string, unknown> }, { file: 'uses-receipt.json', name: 'uses-receipt', doc: uses as Record<string, unknown> }, { file: 'walls-receipt.json', name: 'walls-receipt', doc: walls as Record<string, unknown> }]
